### ISSUE TITLE
recog plugin saves mistaken voice

### ISSUE THREAD

**Issue by lizhenghn123** [unispeech/unimrcp#178]
When i use recog plugin(copy from demorecog), i receive voice data from IVR, and then save it to local disk, it is ok in most cases. But today i find that it saves some mistaken slience, yet it's communicate with a new IVR. And i capture the pcap, there are no slience, like this:
![Uploading unimrcp_tcpdump_wrong.png…]()

Is something wrong?

Thank you!

**Comment by lizhenghn123** [comment]
![Uploading unimrcp_tcpdump_wrong.png…]()

**Comment by achaloyan** [comment]
You may need to increase the playout delay in the jitter buffer to accommodate network variations. Or simply filter out silence frames in your plugin.

(if(frame->type & MEDIA_FRAME_TYPE_AUDIO) == MEDIA_FRAME_TYPE_AUDIO)
      //process frame

**Comment by lizhenghn123** [comment]
Thanks very much for your reply. 
Yes, i had used the second choice,  
if((frame->type& MEDIA_FRAME_TYPE_AUDIO) !=  MEDIA_FRAME_TYPE_AUDIO)       return; 

But i don't know the reason exactly. It seems that the socket returned when some events happened, and then memset buffer with 0, because it's not valid audio data?

I find it in https://github.com/unispeech/unimrcp/blob/master/libs/mpf/src/mpf_bridge.c#L45-L51

I repoened this issue, and look forward to your further reply.

**Comment by lizhenghn123** [comment]
Thanks very much for your reply. 
Yes, i had used the second choice:
if((frame->type& MEDIA_FRAME_TYPE_AUDIO) !=  MEDIA_FRAME_TYPE_AUDIO)       return; 

But i don't know the reason exactly. It seems that the socket returned when some events happened, and then memset buffer with 0, because it's not valid audio data?

I find it in https://github.com/unispeech/unimrcp/blob/master/libs/mpf/src/mpf_bridge.c#L45-L51

I repoened this issue, and look forward to your further reply.

**Comment by achaloyan** [comment]
In the code you referred to, the buffer is filled with 0 only when frame.type is not audio as follows

if((bridge->frame.type & MEDIA_FRAME_TYPE_AUDIO) == 0) {

These frames you should have filtered out. So, I'm not sure what your problem is.

**Comment by lizhenghn123** [comment]
Thank you!
