### ISSUE TITLE
Problema ao comunicar com MRCP erro 503

### ISSUE THREAD

**Issue by rbdelfrate** [unispeech/unimrcp#179]
-- Executing [rbarone@gvt:1] Answer("SIP/rbarone-00000000", "") in new stack
    -- Executing [rbarone@gvt:2] MRCPRecog("SIP/rbarone-00000000", "file://tmp/grammar/fastway.xml,nit=1000&b=1&ct=0.7") in new stack
[Sep 25 16:57:08] NOTICE[14220][C-00000000]: app_mrcprecog.c:1067 app_recog_exec: MRCPRecog() grammar: file://tmp/grammar/fastway.xml
[Sep 25 16:57:08] NOTICE[14220][C-00000000]: app_mrcprecog.c:1087 app_recog_exec: MRCPRecog() options: nit=1000&b=1&ct=0.7
[Sep 25 16:57:08] NOTICE[14220][C-00000000]: src/mrcp_application.c:96 : Create MRCP Handle 0x7f6f4c014418 [speech-nuance5-mrcp1]
[Sep 25 16:57:08] NOTICE[14220][C-00000000]: src/mrcp_client_session.c:133 : Create Channel ASR-0 <new>
[Sep 25 16:57:08] NOTICE[14201]: src/mrcp_client_session.c:387 : Receive App Request ASR-0 <new> [2]
[Sep 25 16:57:08] NOTICE[14201]: src/rtsp_client.c:298 : Create RTSP Handle 0x7f6f2800b498
[Sep 25 16:57:08] NOTICE[14201]: src/mrcp_client.c:700 : Add MRCP Handle ASR-0 <new>
[Sep 25 16:57:08] NOTICE[14201]: src/mrcp_client_session.c:719 : Add Control Channel ASR-0 <new@speechrecog>
[Sep 25 16:57:08] NOTICE[14201]: src/mrcp_client_session.c:411 : Send Offer ASR-0 <new> [c:0 a:1 v:0] to 192.168.2.48:4900
[Sep 25 16:57:08] NOTICE[14204]: src/rtsp_client.c:374 : Established RTSP Connection 192.168.2.79:50179 <-> 192.168.2.48:4900
[Sep 25 16:57:08] NOTICE[14204]: src/rtsp_client.c:573 : Add RTSP Handle 0x7f6f2800b498
[Sep 25 16:57:08] NOTICE[14204]: src/rtsp_client.c:839 : Send RTSP Data 192.168.2.79:50179 <-> 192.168.2.48:4900 [372 bytes]
SETUP rtsp://192.168.2.48:4900/media/speechrecognizer RTSP/1.0
CSeq: 1
Transport: RTP/AVP;unicast;client_port=4000-4001
Content-Type: application/sdp
Content-Length: 195

v=0
o=Asterisk 0 0 IN IP4 192.168.2.79
s=-
c=IN IP4 192.168.2.79
t=0 0
m=audio 4000 RTP/AVP 0 8 96
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:96 L16/8000
a=sendonly
a=ptime:20

[Sep 25 16:57:08] NOTICE[14204]: src/rtsp_client.c:526 : Push RTSP Request to In-Progress Queue 0x7f6f2800b498 <new> CSeq:1
[Sep 25 16:57:13] NOTICE[14204]: src/rtsp_client.c:937 : Receive RTSP Data 192.168.2.79:50179 <-> 192.168.2.48:4900 [47 bytes]
RTSP/1.0 500 Internal Server Error
CSeq: 1

[Sep 25 16:57:13] NOTICE[14204]: src/rtsp_client.c:551 : Pop In-Progress RTSP Request 0x7f6f2800b498 CSeq:1
[Sep 25 16:57:13] NOTICE[14201]: src/mrcp_client_session.c:151 : Receive Answer ASR-0 <new> [c:0 a:0 v:0] Status 0
[Sep 25 16:57:13] NOTICE[14201]: src/mrcp_client_session.c:455 : Raise App Response ASR-0 <new> [2] FAILURE [2]
[Sep 25 16:57:13] ERROR[14201]: app_mrcprecog.c:286 speech_on_channel_add: (ASR-0) Channel error status=2, response code=0!
[Sep 25 16:57:13] NOTICE[14201]: src/mrcp_client_session.c:387 : Receive App Request ASR-0 <new> [1]
[Sep 25 16:57:13] NOTICE[14201]: src/mrcp_client_session.c:833 : Terminate Session ASR-0 <new>
[Sep 25 16:57:13] NOTICE[14204]: src/rtsp_client.c:442 : Remove RTSP Handle 0x7f6f2800b498
[Sep 25 16:57:13] NOTICE[14204]: src/rtsp_client.c:305 : Destroy RTSP Handle 0x7f6f2800b498
[Sep 25 16:57:13] NOTICE[14204]: src/rtsp_client.c:382 : Close RTSP Connection 192.168.2.79:50179 <-> 192.168.2.48:4900
[Sep 25 16:57:13] NOTICE[14204]: src/rtsp_client.c:432 : Destroy RTSP Connection 192.168.2.79:50179 <-> 192.168.2.48:4900
[Sep 25 16:57:13] NOTICE[14201]: src/mrcp_client_session.c:209 : Session Terminated ASR-0 <new>
[Sep 25 16:57:13] NOTICE[14201]: src/mrcp_client.c:710 : Remove MRCP Handle ASR-0 <new>
[Sep 25 16:57:13] NOTICE[14201]: src/mrcp_client_session.c:455 : Raise App Response ASR-0 <new> [1] SUCCESS [0]
[Sep 25 16:57:13] NOTICE[14201]: src/mrcp_application.c:182 : Destroy MRCP Handle ASR-0
[Sep 25 16:57:13] NOTICE[14220][C-00000000]: app_mrcprecog.c:1027 mrcprecog_exit: MRCPRecog() exiting status: ERROR on SIP/rbarone-00000000
  == Spawn extension (gvt, rbarone, 2) exited non-zero on 'SIP/rbarone-00000000'

**Comment by achaloyan** [comment]
I don't see anything wrong in the client request which could made the server respond with

`
RTSP/1.0 500 Internal Server Error
CSeq: 1
`

The problem is most probably on the server side.
