### ISSUE TITLE
Compile fails - Undefined reference to `apr_pool_mutex_set'

### ISSUE THREAD

**Issue by seifertm** [unispeech/unimrcp#181]
Hi!

I am trying to package UniMRCP for Gentoo Linux.
When compiling v1.2 or v1.3, I got an error message about an undefined reference to ``apr_pool_mutex_set``.

The system is using apr-1.5.2 and apr-util-1.5.4. Both are found by the configure step and the library versions should be okay according to the instructions in the ``INSTALL`` file.
Moreover other applications that depend on apr install and operate just fine.

Do I need to downgrade either apr library? Any ideas?

**Comment by pannzh** [comment]
I got the same problem too. I tried to find the spesific interface in the apr source, but it returned nothing.

```
grep -i "apr_pool_mutex_set" -r apr-1.5.2
grep -i "apr_pool_mutex_set" -r apr-util-1.5.4
```

However, 

    grep "apr_pool_mutex_set" -r unimrcp-deps-1.3.0

shows
```
unimrcp-deps-1.3.0/libs/apr/memory/unix/apr_pools.c:APR_DECLARE(void) apr_pool_mutex_set(apr_pool_t *pool,
unimrcp-deps-1.3.0/libs/apr/include/apr_pools.h:APR_DECLARE(void) apr_pool_mutex_set(apr_pool_t *pool,
```

So maybe downgrade the library would fix this. In fact, you should install dependencies through  [build-dep-libs.sh](http://www.unimrcp.org/downloads/dependencies), rather than by yourself.

**Comment by blerest** [comment]
> So maybe downgrading the library(apr-1.5.2 to apr-1.5.1) would fix this. In fact, you should install dependencies through build-dep-libs.sh, rather than by yourself.

You are true, that fixed the issue for me.

**Comment by seifertm** [comment]
Thanks for sharing your solutions.

Since I wanted to create a package for Gentoo Linux, I did not even try to use `build-dep-libs.sh`. If I include bundled dependencies like this in the UniMRCP package, it is highly unlikely to get accepted.

**Comment by achaloyan** [comment]
The requirement of having thread-safe APR memory pools has been discussed many times down the road. Unfortunately, the official distribution of the APR library does not satisfy the requirement, that's why a patched version distributed with the UniMRCP dependencies has to be used.
