### ISSUE TITLE
Rtp Port range have to be an even length in the configuration file

### ISSUE THREAD

**Issue by MertBuyuktuncay** [unispeech/unimrcp#182]
OS: independent - we tested on windows
version: 1.0 (bug still exists in the master branch)

What steps will reproduce the problem?
1-use rtp port range [5100,5111] in the unimrcpserver.xml
2-start unimrcpserver.exe
3-perform several recognition operations.(for this we used unimrcpclient.exe)
4-you will receive a log similar to the following: 
(for brevity I've trimmed down the log lines)

[INFO]   Open RTP Receiver 192.168.10.140:5100 <- 192.168.10.140:4000 
[INFO]   Open RTP Receiver 192.168.10.140:5102 <- 192.168.10.140:4000 
[INFO]   Open RTP Receiver 192.168.10.140:5104 <- 192.168.10.140:4000 
[INFO]   Open RTP Receiver 192.168.10.140:5106 <- 192.168.10.140:4000 
[INFO]   Open RTP Receiver 192.168.10.140:5108 <- 192.168.10.140:4000 
[INFO]   Open RTP Receiver 192.168.10.140:5110 <- 192.168.10.140:4000 
[INFO]   Open RTP Receiver 192.168.10.140:5112 <- 192.168.10.140:4000 
[INFO]   Open RTP Receiver 192.168.10.140:5114 <- 192.168.10.140:4000 
[INFO]   Open RTP Receiver 192.168.10.140:5116 <- 192.168.10.140:4000 

You can also get a similar effect if you use rtp port interval [5101,5112]

this indicates that the problem is the length of the interval ie. the number of rtp ports specified here should be an even number.

I've also found the location that is responsible for this check.
https://github.com/unispeech/unimrcp/blob/master/libs/mpf/src/mpf_rtp_stream.c#L178

this can be fixed by using < instead of ==.

Regards
Mert

**Comment by achaloyan** [comment]
Hi Mert,

Thanks for the detailed and clear description of the problem.

While the port range is indeed supposed to be configured to contain even number of ports, the procedure should not cross the specified border even if the number of ports is odd. The problem has been fixed.

I apologize for the late response, just got a chance to look into this.

Regards,
Arsen

**Comment by MertBuyuktuncay** [comment]
>I apologize for the late response, just got a chance to look into this.
no problem

As always thanks for good software
