### ISSUE TITLE
Error in capturing DTMF String

### ISSUE THREAD

**Issue by anujitbhu** [unispeech/unimrcp#183]
Hi,

I am using unimrcp along with Asterisk and Nuance ASR . Idea is to capture the ten digit mobile number over speech and DTMF .
When I try to capture over DTMF it says no input . Mrcp trace is as follows:-
    -- AGI Script Executing Application: (MRCPRecog) Options: (builtin:dtmf/number?minlength=10,dtt=5000&b=1&ct=0.7&spl=en-IN&f=/home/project/prompt/pension/welcome)

[Jan 10 00:48:01] NOTICE[14416]: app_mrcprecog.c:1067 app_recog_exec: MRCPRecog() grammar: builtin:dtmf/number?minlength=10

[Jan 10 00:48:01] NOTICE[14416]: app_mrcprecog.c:1087 app_recog_exec: MRCPRecog() options: dtt=5000&b=1&ct=0.7&spl=en-IN&f=/home/project/prompt/pension/welcome

[Jan 10 00:48:01] NOTICE[14416]: src/mrcp_application.c:96 : Create MRCP Handle 0x9a0e148 [speech-nuance5-mrcp2]

[Jan 10 00:48:01] NOTICE[14416]: src/mrcp_client_session.c:133 : Create Channel ASR-11 <new>

[Jan 10 00:48:01] NOTICE[14180]: src/mrcp_client_session.c:387 : Receive App Request ASR-11 <new> [2]

[Jan 10 00:48:01] NOTICE[14180]: src/mrcp_client.c:700 : Add MRCP Handle ASR-11 <new>

[Jan 10 00:48:01] NOTICE[14180]: src/mrcp_client_session.c:719 : Add Control Channel ASR-11 <new@speechrecog>

[Jan 10 00:48:01] NOTICE[14180]: src/mrcp_client_session.c:411 : Send Offer ASR-11 <new> [c:1 a:1 v:0] to 180.151.100.99:5070

[Jan 10 00:48:01] NOTICE[14180]: src/mrcp_sofiasip_client_agent.c:354 : Local SDP ASR-11 <new>

v=0

o=Asterisk 0 0 IN IP4 180.151.100.98

s=-

c=IN IP4 180.151.100.98

t=0 0

m=application 9 TCP/MRCPv2 1

a=setup:active

a=connection:new

a=resource:speechrecog

a=cmid:1

m=audio 4022 RTP/AVP 0 8 96 101

a=rtpmap:0 PCMU/8000

a=rtpmap:8 PCMA/8000

a=rtpmap:96 L16/8000

a=rtpmap:101 telephone-event/8000

a=fmtp:101 0-15

a=sendonly

a=ptime:20

a=mid:1

[Jan 10 00:48:01] NOTICE[14184]: src/mrcp_sofiasip_client_agent.c:609 : Receive SIP Event [nua_i_state] Status 0 INVITE sent [speech-nuance5-mrcp2]

[Jan 10 00:48:01] NOTICE[14184]: src/mrcp_sofiasip_client_agent.c:547 : SIP Call State ASR-11 [calling]

[Jan 10 00:48:01] NOTICE[14184]: src/mrcp_sofiasip_client_agent.c:609 : Receive SIP Event [nua_r_invite] Status 200 OK [speech-nuance5-mrcp2]

[Jan 10 00:48:01] NOTICE[14184]: src/mrcp_sofiasip_client_agent.c:609 : Receive SIP Event [nua_i_state] Status 200 OK [speech-nuance5-mrcp2]

[Jan 10 00:48:01] NOTICE[14184]: src/mrcp_sofiasip_client_agent.c:547 : SIP Call State ASR-11 [ready]

[Jan 10 00:48:01] NOTICE[14184]: src/mrcp_sofiasip_client_agent.c:433 : Remote SDP ASR-11 <new>

v=0

o=- 1452366009 1452366009 IN IP4 180.151.100.99

s=Nuance MRCP session V2

c=IN IP4 180.151.100.99

t=0 0

m=application 6075 TCP/MRCPv2 1

a=cmid:1

a=setup:passive

a=connection:new

a=channel:22@speechrecog

m=audio 7934 RTP/AVP 0 8 96 101

a=rtpmap:0 pcmu/8000

a=rtpmap:8 pcma/8000

a=rtpmap:96 l16/8000

a=rtpmap:101 telephone-event/8000

a=fmtp:101 0-15

a=recvonly

a=ptime:20

a=mid:1

[Jan 10 00:48:01] NOTICE[14180]: src/mrcp_client_session.c:151 : Receive Answer ASR-11 <new> [c:1 a:1 v:0] Status 200

[Jan 10 00:48:01] NOTICE[14184]: src/mrcp_sofiasip_client_agent.c:609 : Receive SIP Event [nua_i_active] Status 200 Call active [speech-nuance5-mrcp2]

[Jan 10 00:48:01] NOTICE[14181]: src/mrcp_client_connection.c:338 : Established TCP/MRCPv2 Connection 180.151.100.98:55093 <-> 180.151.100.99:6075

[Jan 10 00:48:01] NOTICE[14181]: src/mrcp_client_connection.c:435 : Add Control Channel <22@speechrecog> 180.151.100.98:55093 <-> 180.151.100.99:6075 [1]

[Jan 10 00:48:01] NOTICE[14182]: src/mpf_rtp_stream.c:331 : Enable RTP Session 180.151.100.98:4022

[Jan 10 00:48:01] NOTICE[14182]: src/mpf_rtp_stream.c:921 : Open RTP Transmitter 180.151.100.98:4022 -> 180.151.100.99:7934

[Jan 10 00:48:01] NOTICE[14182]: src/mpf_bridge.c:93 : Media Path ASR-11 Source->[PCMA/8000/1]->Decoder->[LPCM/8000/1]->Bridge->[LPCM/8000/1]->Encoder->[PCMU/8000/1]->Sink

[Jan 10 00:48:01] NOTICE[14180]: src/mrcp_client_session.c:455 : Raise App Response ASR-11 <22> [2] SUCCESS [0]

[Jan 10 00:48:01] NOTICE[14180]: app_mrcprecog.c:279 speech_on_channel_add: (ASR-11) Channel ready codec=PCMA, sample rate=8000

[Jan 10 00:48:01] NOTICE[14416]: app_mrcprecog.c:1295 app_recog_exec: (ASR-11) Recognizing, enable DTMFs: 2, start input timers: 0

[Jan 10 00:48:01] NOTICE[14180]: src/mrcp_client_session.c:392 : Receive App MRCP Request ASR-11 <22>

[Jan 10 00:48:01] NOTICE[14180]: src/mrcp_client_session.c:622 : Send MRCP Request ASR-11 <22@speechrecog> [1]

[Jan 10 00:48:01] NOTICE[14181]: src/mrcp_client_connection.c:530 : Send MRCPv2 Data 180.151.100.98:55093 <-> 180.151.100.99:6075 [272 bytes]

MRCP/2.0 272 RECOGNIZE 1

Channel-Identifier: 22@speechrecog

Content-Type: text/uri-list

Cancel-If-Queue: false

Start-Input-Timers: false

Dtmf-Term-Timeout: 5000

Confidence-Threshold: 0.7

Speech-Language: en-IN

Content-Length: 32

builtin:dtmf/number?minlength=10

[Jan 10 00:48:01] NOTICE[14181]: src/mrcp_client_connection.c:635 : Receive MRCPv2 Data 180.151.100.98:55093 <-> 180.151.100.99:6075 [69 bytes]

MRCP/2.0 69 1 200 IN-PROGRESS

Channel-Identifier: 22@speechrecog

[Jan 10 00:48:01] NOTICE[14180]: src/mrcp_client_session.c:500 : Raise App MRCP Response ASR-11 <22>

[Jan 10 00:48:01] NOTICE[14416]: speech_channel.c:731 astchan_stream_file: Stream file /home/project/prompt/pension/welcome on SIP/tatasip-00000019 length:166737

[Jan 10 00:48:06] NOTICE[14182]: src/mpf_rtp_stream.c:1199 : Generate RTCP SR [ssrc:2415541635 s:186 o:29760 ts:38800]

[Jan 10 00:48:06] NOTICE[14182]: src/mpf_rtp_stream.c:1386 : Send Compound RTCP Packet [BYE] [80 bytes] 180.151.100.98:4023 -> 180.151.100.99:7935

[Jan 10 00:48:06] NOTICE[14181]: src/mrcp_client_connection.c:635 : Receive MRCPv2 Data 180.151.100.98:55093 <-> 180.151.100.99:6075 [124 bytes]

MRCP/2.0 124 RECOGNITION-COMPLETE 1 COMPLETE

Channel-Identifier: 22@speechrecog

Completion-Cause: 002 no-input-timeout

[Jan 10 00:48:06] NOTICE[14180]: src/mrcp_client_session.c:516 : Raise App MRCP Event ASR-11 <22>

[Jan 10 00:48:06] NOTICE[14180]: src/mrcp_client_session.c:387 : Receive App Request ASR-11 <22> [1]

[Jan 10 00:48:06] NOTICE[14180]: src/mrcp_client_session.c:833 : Terminate Session ASR-11 <22>

[Jan 10 00:48:06] NOTICE[14181]: src/mrcp_client_connection.c:459 : Remove Control Channel <22@speechrecog> [0]

[Jan 10 00:48:06] NOTICE[14181]: src/mrcp_client_connection.c:386 : Close TCP/MRCPv2 Connection 180.151.100.98:55093 <-> 180.151.100.99:6075

[Jan 10 00:48:06] NOTICE[14182]: src/mpf_rtp_stream.c:935 : Close RTP Transmitter 180.151.100.98:4022 -> 180.151.100.99:7934 [s:186 o:29760]

[Jan 10 00:48:06] NOTICE[14182]: src/mpf_rtp_stream.c:418 : Remove RTP Session 180.151.100.98:4022

[Jan 10 00:48:06] NOTICE[14182]: src/mpf_rtp_stream.c:1199 : Generate RTCP SR [ssrc:2415541635 s:186 o:29760 ts:39120]

[Jan 10 00:48:06] NOTICE[14182]: src/mpf_rtp_stream.c:1386 : Send Compound RTCP Packet [BYE] [80 bytes] 180.151.100.98:4023 -> 180.151.100.99:7935

[Jan 10 00:48:06] NOTICE[14184]: src/mrcp_sofiasip_client_agent.c:609 : Receive SIP Event [nua_r_bye] Status 200 OK [speech-nuance5-mrcp2]

[Jan 10 00:48:06] NOTICE[14184]: src/mrcp_sofiasip_client_agent.c:609 : Receive SIP Event [nua_i_state] Status 200 to BYE [speech-nuance5-mrcp2]

[Jan 10 00:48:06] NOTICE[14184]: src/mrcp_sofiasip_client_agent.c:547 : SIP Call State ASR-11 [terminated]

[Jan 10 00:48:06] NOTICE[14180]: src/mrcp_client_session.c:209 : Session Terminated ASR-11 <22>

[Jan 10 00:48:06] NOTICE[14180]: src/mrcp_client_connection.c:235 : Destroy TCP/MRCPv2 Connection 180.151.100.98:55093 <-> 180.151.100.99:6075

[Jan 10 00:48:06] NOTICE[14180]: src/mrcp_client.c:710 : Remove MRCP Handle ASR-11 <22>

[Jan 10 00:48:06] NOTICE[14180]: src/mrcp_client_session.c:455 : Raise App Response ASR-11 <22> [1] SUCCESS [0]

[Jan 10 00:48:06] NOTICE[14180]: src/mrcp_application.c:182 : Destroy MRCP Handle ASR-11

[Jan 10 00:48:06] NOTICE[14416]: app_mrcprecog.c:1027 mrcprecog_exit: MRCPRecog() exiting status: OK on SIP/tatasip-00000019

    -- <SIP/tatasip-00000019>AGI Script main.php completed, returning 4

Please suggest where I am wrong .

Rg

Anuj

**Comment by achaloyan** [comment]
Hi Anuj,

Not sure if you could resolve the problem, but I do not see any DTMFs passed from Asterisk to the MRCP client to be further transmitted to the server.

Normally, you should see the following log statements once a DTMF is pressed.

app_synthandrecog.c:1713 app_synthandrecog_exec: (ASR-2) User pressed DTMF key (55)
app_synthandrecog.c:1720 app_synthandrecog_exec: (ASR-2) DTMF digit queued (7)
app_synthandrecog.c:1051 recog_stream_read: (ASR-2) DTMF frame written
