### ISSUE TITLE
Illegal Value Header Field Nuance Mrcpv2 Dtmf-interdigit-timeout :3s

### ISSUE THREAD

**Issue by dfmaiquez** [unispeech/unimrcp#185]
When unimrcp send RECOGNIZE message, Dtmf-interdigit-timeout and  header is add with this format:

Dtmf-Interdigit-Timeout: 3s
Dtmf-Term-Timeout: 0s

And Nuance Speech Recognizer response with: 
MRCP/2.0 119 3 404 COMPLETE
Dtmf-Interdigit-Timeout: 3s
Dtmf-Term-Timeout: 0s
Channel-Identifier: 28@speechrecog

Because nuance not support time with letter s, The server wait the value in ms without unit. 
How can i solve this problem, sorry?

**Comment by achaloyan** [comment]
You didn't mention how UniMRCP is used. If by means of direct API calls, then you may consider the following fragment of code:

`pRecogHeader->dtmf_interdigit_timeout = 3000;
mrcp_resource_header_property_add(pMrcpMessage,RECOGNIZER_HEADER_DTMF_INTERDIGIT_TIMEOUT);`

Also, you may use the following code as a reference.

[https://github.com/unispeech/unimrcp/blob/master/platforms/umc/src/setparamsession.cpp]
