### ISSUE TITLE
unimrcp / asterisk crashes cause #11

### ISSUE THREAD

**Issue by axelbower** [unispeech/unimrcp#187]
*_What steps will reproduce the problem? *_
1. Several time a day a seemingly random unimrcp cause asterisk to sig 11. 
2. This machine handles only SIP incoming calls.

*_What version of the product are you using? On what operating system? *_
- Asterisk GIT-13-fcb6c17M
- unimrcp 1.3
- uni-ast-package 1.3.1
- debian 6.0.4 
- NNS 5.1.8 / Nuance recognizer 9

[backtrace1.txt](https://github.com/unispeech/unimrcp/files/108393/backtrace1.txt)

**Comment by achaloyan** [comment]
How the problem can be reproduced? Can you provide logs for common scenario in use?

**Comment by achaloyan** [comment]
This issue is being closed due to inactivity. The source of the reported problem remains unknown.
