### ISSUE TITLE
STOP response message length is incorrect

### ISSUE THREAD

**Issue by MertBuyuktuncay** [unispeech/unimrcp#190]
OS: independent - we tested on windows
version: 1.3 (bug still exists in 1.4 and in the master branch)
What steps will reproduce the problem?
a- start a recognition
b- call stop on the recognition
c- observe the response to the STOP message.

assume there is a RECOGNIZE request with request id =5

then for the following STOP request :
MRCP/2.0 79       STOP  6
Channel-Identifier: 7351afae2191fc46@speechrecog

The following response is generated:
MRCP/2.0 117 6 200 COMPLETE
Channel-Identifier: 7351afae2191fc46@speechrecog
Active-Request-Id-List: 5

If you count the number of characters(including new lines) the message length should have been 108 but it is written here as 117.
The cause seems to be the following commit:
https://github.com/unispeech/unimrcp/commit/523ed4bdb06be0bfbdb23d54e47635e7daec8b11#diff-6e12b171e28c4372e285839415a73c6a

The string buffer size for this integer conversion has been treated as the actual string size. 

solution:
if we add the following line 
	`str->length = pos - str->buf;`
to the following location in code.
https://github.com/unispeech/unimrcp/blob/master/libs/mrcp/message/src/mrcp_generic_header.c#L85

the problem should be fixed.

Regards
Mert Büyüktuncay

**Comment by achaloyan** [comment]
Great finding. Thanks Mert. I have added you as a contributor to the AUTHORS file.

94d4b1f37a49dcda3da6e0213a159e27c4cf72a3

**Comment by MertBuyuktuncay** [comment]
As always, thank you for great software. (and also for adding me as an author)

Oh by the way this issue caused integration problems with cisco cvp, if anyone is interested the details are:
- cvp consumes more than actual STOP message actual length during STOP call.
- The during the next RECOGNIZE request cvp does not accept the MRCP message format (due to the missing character in the beginning)
- cvp throws something like a message format exception internally. unimrcpserver observes that the IVR has been suddenly disconnected.
- The IVR client gets a no resource error. It seems due to this issue cvp thinks mrcp sr server is not functioning properly.

**Comment by achaloyan** [comment]
Well, good to know all these details!
