### ISSUE TITLE
Failed to load MRCP server plugin

### ISSUE THREAD

**Issue by pannzh** [unispeech/unimrcp#191]
Hi,all

I've test the demo project  unimrcp-server and it's demo_recog_engine.c plugin. It works fine until I try to add some other c++ source files to implement the real recog_engine. I compiled and linked those file into libdemorecog.so, however when I started the mrcp server, It failed to load my plugin. And here is my log output:

[WARN]   Failed to Load DSO: /path/to/plugin/libdemorecog.so: undefined symbol: _ZNK6google8protobuf7Message11GetTypeNameEv

I've not even changed the demo_recog_engine.c file but only link it with other .cpp files. I wonder if we can write mrcp server plugin in c++ ? or not ?

**Comment by pannzh** [comment]
Oh, sorry I've made a mistake, that I forgot to link protobuf library which I used.

**Comment by shanghai-Jerry** [comment]
how to fix

**Comment by achaloyan** [comment]
You need to link the library that contains the missing symbols.

**Comment by shanghai-Jerry** [comment]
> You need to link the library that contains the missing symbols.

i have no ideas about the missing library
