### ISSUE TITLE
The correct way to specify server ip at runtime?

### ISSUE THREAD

**Issue by pannzh** [unispeech/unimrcp#192]
As we're running unimrcp client, I know that we could specify the mrcp server profile in conf/client-profiles/xxx.xml, but how can I change the setting such as ip address or sip-port at runtime? Is there any example or document?

**Comment by achaloyan** [comment]
Currently, it is not possible to change the mentioned parameters via API at run-time.

**Comment by gcamp0730** [comment]
We have our client connect to a server running opensips.  The opensips server will route the connection to one of several other servers.  That way we can dynamically change the IP w/o having to change the config file on the client.

**Comment by achaloyan** [comment]
The same can be achieved having defined multiple profiles in the client configuration (let's say one per server) and selecting one of the profiles using round-robin or based on a different criteria. In this case, the server/profile selection is bound to a user application.
