### ISSUE TITLE
Session Based Logging

### ISSUE THREAD

**Issue by BurhanEyimaya** [unispeech/unimrcp#194]
Hi,

In our plugin we want to write logs of every session to different files.
We have used the **apt_log_ext_handler_set** method to set a log handler.
But in this handler method how can we know which session this log belongs?
Is there another way to do session based logging?

Thanks,
Burhan Eyimaya

**Comment by achaloyan** [comment]
This question has been answered on the discussion group

https://groups.google.com/forum/?fromgroups#!topic/unimrcp/oIkWqH-RBec
