### ISSUE TITLE
undefined reference to `XML_StopParser'

### ISSUE THREAD

**Issue by mradul17** [unispeech/unimrcp#195]
i got this error 
/usr/local/apr/lib/libaprutil-1.so: undefined reference to `XML_StopParser'

when i am doing make on centos machine

**Comment by achaloyan** [comment]
It looks like your system-wide version of expat is not compatible with apr-util.

While building the dependencies, in particular the apr-util library, you may specify the built-in version of expat shipped with apr-util.

./configure --with-expat=builtin

**Comment by achaloyan** [comment]
Having no follow-up response, the problem presumably has been addressed.

**Comment by slvtn** [comment]
Hello, im havin' same issue
Before building deps (/build-dep-libs.sh) im reconfigured apr-utils configration as you said before (./configure --with-expat=builtin)
After building deps im executed bootstrap, configuration and on make step im having 
/usr/local/apr/lib/libaprutil-1.so: undefined reference to `XML_StopParser'

**Comment by achaloyan** [comment]
In build-dep-libs.sh, the configure line in build_apu() should look like

./configure --with-apr=${APR_SRCDIR} **--with-expat=builtin** --prefix=${APR_INSTALLDIR}

If you had already built the library, then use `make distclean` or simply start over having the above change applied, it should make the difference.

**Comment by mcgrady-forever** [comment]
> In build-dep-libs.sh, the configure line in build_apu() should look like
> 
> ./configure --with-apr=${APR_SRCDIR} **--with-expat=builtin** --prefix=${APR_INSTALLDIR}
> 
> If you had already built the library, then use `make distclean` or simply start over having the above change applied, it should make the difference.

I encountered the same problem after i did as what u have said

/usr/local/apr/lib/libaprutil-1.so: undefined reference to `XML_StopParser'

**Comment by achaloyan** [comment]
Maybe you can debug this issue further with the help of ldd in order to check which expat library is actually used.

ldd /usr/local/apr/lib/libaprutil-1.so

**Comment by mcgrady-forever** [comment]
> Maybe you can debug this issue further with the help of ldd in order to check which expat library is actually used.
> 
> ldd /usr/local/apr/lib/libaprutil-1.so

	linux-vdso.so.1 =>  (0x00007fff583c3000)
	libexpat.so.0 => /usr/local/apr/lib/libexpat.so.0 (0x00007f2ca4efe000)
	libapr-1.so.0 => /usr/local/apr/lib/libapr-1.so.0 (0x00007f2ca4cca000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f2ca4aad000)
	libcrypt.so.1 => /lib64/libcrypt.so.1 (0x00007f2ca4876000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f2ca4659000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f2ca4455000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f2ca4092000)
	libfreebl3.so => /lib64/libfreebl3.so (0x00007f2ca3e8e000)
	/lib64/ld-linux-x86-64.so.2 (0x000055cb0719f000)


It seems that expat library I used is correct

**Comment by achaloyan** [comment]
I would guess the library at /usr/local/apr/lib/libexpat.so.0 was not installed with the apr libraries from dependecies. Simply remove or rename that library and try the same over.

**Comment by mcgrady-forever** [comment]
> I would guess the library at /usr/local/apr/lib/libexpat.so.0 was not installed with the apr libraries from dependecies. Simply remove or rename that library and try the same over.

I user another libexpat version and it works

**Comment by mxx1219** [comment]
> > I would guess the library at /usr/local/apr/lib/libexpat.so.0 was not installed with the apr libraries from dependecies. Simply remove or rename that library and try the same over.
> 
> I user another libexpat version and it works

Hello, I met the same problem, and could you explain how to use another libexpat version? I don't know how to handle it. Thanks!
