### ISSUE TITLE
UniMRCP client integration with Naunce 

### ISSUE THREAD

**Issue by VipulSabale** [unispeech/unimrcp#198]
Hi ,

I want to write client using unimrcp  for Naunce speech server. I am lost here from where to start.
Can any one guide me on this ?

**Comment by achaloyan** [comment]
Visit the [MRCP Client Integration](http://unimrcp.org/solutions/client) page.

Check out the client integration guide first and also see how sample applications have been implemented: platforms/umc and/or platforms/unimrcp-client.
