### ISSUE TITLE
configure script fails due to missing pkg-config without proper error message

### ISSUE THREAD

**Issue by greenfieldtech-nirs** [unispeech/unimrcp#199]
When trying to build either the release or the Master, if pkg-config is missing from the system - the ./configure script will fail without a proper error message. It will eventually fail at line 18357, on the following:

```
as_fn_error looked for libsofia-sip-ua in $sofia_path "Cannot find Sofia-SIP - pkg-config not available" "$LINENO" 5
```

While the configure script says "pkg-config not available", the output of the configure will show this:

```
checking for Sofia-SIP... Looking for sofia at
./configure: line 418: test: looked: integer expression expected
configure: error: for
./configure: line 307: return: looked: numeric argument required
./configure: line 317: exit: looked: numeric argument required
```

Which doesn't provide much useful information, unless you start digging into the configure script to figure out what went wrong. 

Correction: Add pkg-config as part of the prerequisites to unimrcp core compilation, and/or provide a more meaningful response on this dep missing.

**Comment by achaloyan** [comment]
Well, while the installation instructions do have pkg-config among prerequisites, I agree that it would be better, if ./configure itself could provide more reasonable output. Addressed in fa54c561e20cba142c5f0a68726f70f1babc70a1.

Thanks for your feedback.
