### ISSUE TITLE
unimrcp hangup during session startup

### ISSUE THREAD

**Issue by MertBuyuktuncay** [unispeech/unimrcp#202]
OS: we use windows x64 
version: we observed this in 1.3 and in a version between 1.4 and latest trunk
What steps will reproduce the problem?
start unimrcpserver.exe with our custom sr plugin 
try to establish a session. by using either mrcpv1 or mrcpv2
unimrcp server logs the incoming sdp and does something like ignoring the session. it neither calls the plugin about this new session request nor sends a reply to the client side.

This error is rarely observed. So much that we could not reproduce this in our side while unimrcp debug logs are open. Possibly a multithreading issue?

sample server logs are 
 - note that 5 seconds after sending the sdp, the client side gives up its hope and disconnects.

2017-08-24 10:39:26:173091 [NOTICE] Accepted RTSP Connection 192.168.205.35:2554 <-> 192.168.205.35:62081
2017-08-24 10:39:26:173091 [INFO]   Receive RTSP Data 192.168.205.35:2554 <-> 192.168.205.35:62081 [332 bytes]
SETUP rtsp://192.168.205.35:2554/media/speechrecognizer RTSP/1.0
CSeq: 1
Transport: RTP/AVP;unicast;client_port=7512
Content-Type: application/sdp
Content-Length: 158

v=0
o=SestekMrcpClient 0 0 IN IP4 192.168.205.35
s=-
c=IN IP4 192.168.205.35
t=0 0
m=audio 7512 RTP/AVP 0
a=rtpmap:0 PCMU/8000
a=sendonly
a=ptime:20

2017-08-24 10:39:26:174088 [NOTICE] Create RTSP Session <d204a6f995b5694c>
2017-08-24 10:39:26:174088 [INFO]   Create Session 0x7b150236d8 <new> [uni1]
2017-08-24 10:39:26:174088 [INFO]   Add RTSP Session <d204a6f995b5694c>
2017-08-24 10:39:31:174479 [INFO]   RTSP Peer Disconnected 192.168.205.35:2554 <-> 192.168.205.35:62081
2017-08-24 10:39:31:175469 [INFO]   Close RTSP Connection 192.168.205.35:2554 <-> 192.168.205.35:62081
2017-08-24 10:39:31:175469 [NOTICE] Terminate Remaining RTSP Sessions [1]

I am working on this issue for a few days and finally determined that the problem occurs inside unimrcpserver.exe because for any new session after the above logs are printed two more log lines appear before the plugin functions are being called. eg.

2017-08-24 16:52:56:479135 [NOTICE] Accepted RTSP Connection 192.168.10.203:2554 <-> 192.168.10.203:47808
2017-08-24 16:52:56:480148 [INFO]   Receive RTSP Data 192.168.10.203:2554 <-> 192.168.10.203:47808 [320 bytes]
SETUP rtsp://192.168.10.203:2554/media/speechrecognizer RTSP/1.0
CSeq: 1
Transport: RTP/AVP;unicast;client_port=58325
Content-Type: application/sdp
Content-Length: 145

v=0
o=SestekMrcpClient 0 0 IN IP4 0.0.0.0
s=-
c=IN IP4 0.0.0.0
t=0 0
m=audio 58325 RTP/AVP 0
a=rtpmap:0 PCMU/8000
a=sendonly
a=ptime:20

2017-08-24 16:52:56:480148 [NOTICE] Create RTSP Session <1ad381c9b90f9c44>
2017-08-24 16:52:56:483146 [INFO]   Create Session 0x7e3f5d65d8 <new> [uni1]
2017-08-24 16:52:56:483146 [INFO]   Add RTSP Session <1ad381c9b90f9c44>
2017-08-24 16:52:56:486473 [NOTICE] Add Session <1ad381c9b90f9c44>
2017-08-24 16:52:56:486981 [INFO]   Receive Offer 0x7e3f5d65d8 <1ad381c9b90f9c44> [c:0 a:1 v:0]

This problem occurred in 3 different customers/installations in last week.
I am a little lost trying to solve it. Can you point me to a direction about where I should check?

Regards
Mert

**Comment by achaloyan** [comment]
Hi Mert,

This is really weird. 

Reading your description, the first thing I would suspect is the message queue. It could be that under certain circumstances a message either is not posted to the message queue or somehow not processed.

I wanted to ask you to set log level to DEBUG, but then noticed that you tried and could not reproduce the problem in that way. So, I wonder if you could change the log level at least for the following two statements to INFO and try again.

[Signal Message](https://github.com/unispeech/unimrcp/blob/master/libs/apr-toolkit/src/apt_task.c#L263)
[Process Message](https://github.com/unispeech/unimrcp/blob/master/libs/apr-toolkit/src/apt_task.c#L335)

Regards,
Arsen

**Comment by MertBuyuktuncay** [comment]
Hi Arsen,
Thanks for the push. I am making my new tests after changing those 2 log levels.

I've noticed that my report above has some missing info. 
- The seemingly ignored session is not the first session unimrcpserver observes. In all the cases until now unimrcp works for some time and then this situation happens. 
- Similar situation is observed with 2 different clients (one is our own mrcpclient and the other is genesys )

Especially I want to share the server log for the error situation I've reported the error. For this log the requests come from our own client.

[unimrcpserver-2017_08_23-15_38_19-0_share_web.txt](https://github.com/unispeech/unimrcp/files/1251084/unimrcpserver-2017_08_23-15_38_19-0_share_web.txt)

In this specific case the server has waited idle for a day, accepted a session(c76cf25576526a47) successfully and this session got terminated 20 minutes later. The next session after this has the error.

Note that in this scenario the client app(IVR) aims to use a single session during its lifetime so the sessions are long lived, which I am not sure I like very much. Termination of the session implies that the client app has been shutdown and making a new session implies that the client app has started. So one possible guess is that some thing may have got stuck during finalization of the previous session, which is probably not a proper termination but a disconnect due to client app being shutdown.

- Another error case was with genesys. In one of our customers it is always the RECOGNIZE message that faces the problem. The reason I think they have the same error is that the behavior is similar albeit not exactly the same. In this case a remote message is logged in unimrcpserver logs but the call to to the sr plugin is observed very late. In one case it has waited 20 seconds before the plugin got the message, normally this duration is smaller than one millisecond.


With all the above info I feel that maybe I shall look into rtp message queue since both session generation and recognize message has something to do with the rtp. May these problems be observed if the sr-plugin somehow has trouble returning from rtp close callback? Or should I only suspect the unimrcpserver side for this. I could not make sure from unimrcpserver logs if the error can be plugin oriented or not.

Regards Mert

**Comment by achaloyan** [comment]
Hi Mert,

The mentioned session (c76cf25576526a47) was not properly terminated. I see a statement Terminate Session, there should be a confirmation/completion Session Terminated, which would follow with Destroy Session.

Upon session termination, all underlying resources are requested to be closed, including the plugin channel. I am almost certain that the plugin callback never returns in this case. That is why a new session is not processed, or partially processed up to the stage where a task message is sent to the core thread for further processing, but never picked up.

Regards,
Arsen

**Comment by MertBuyuktuncay** [comment]
uh oh. Thanks, that seems appropriate. If only I could freely reproduce with debug logs I could have catched that. I will continue working on this and let you know.
Regards

**Comment by MertBuyuktuncay** [comment]
Seems like an extra service was preventing us from closing the channel under stress. I am pretty sure this bug was not caused by unimrcp now. 

Regards
