### ISSUE TITLE
crash during barge-in (not always, sometimes) even with demosynth plugin

### ISSUE THREAD

**Issue by bayramboyraz** [unispeech/unimrcp#203]
This bug could be recreated if a client continuously send tts request and then barge-in request just around the time tts synthesis about to finish. It does not happen immediately. But finally it crashes. It took around 20 minutes to recreate the bug when we send such requests. 

We could see that in the file "libs\mrcp-engine\src\mrcp_synth_state_machine.c"

at line

"342		active_request_id_list_append(generic_header,state_machine->speaker->start_line.request_id);"

speaker was null
[log.zip](https://github.com/unispeech/unimrcp/files/1295162/log.zip)

**Comment by achaloyan** [comment]
Thanks, Bayram. Fixed in 35dbbd557aa9d3fd2bcf0b9601a99e8853a6f892.
