### ISSUE TITLE
A UDP-based SIP session is ended with TCP BYE

### ISSUE THREAD

**Issue by bayramboyraz** [unispeech/unimrcp#205]
Hello Arsen,

A customer informed us about this bug. And here is the SIP messaging log coming from the customer:

[sip.log](https://github.com/unispeech/unimrcp/files/1449842/sip.log)

at line 86 you can see Via: **SIP/2.0/TCP** 10.2.106.162:9060;branch=z9hG4bKX3m3QZ4QD64gH, in the BYE message that is sent by UniMRCP

although SIP session had been started with an INVITE having "Via: **SIP/2.0/UDP** 10.2.106.113:5060;branch=z9hG4bK49796F5"

**Comment by achaloyan** [comment]
Hello Bayram,

I have checked the provided SIP message exchange and noticed that not all the SIP header fields are present in the original SIP INVITE. It is unlikely that Cisco-SIPGateway sends such a malformed INVITE message. Where is the SIP Contact header field?

Sofia-SIP sends a BYE message to the address/transport specified in Contact, which is in accordance with the specification.
