### ISSUE TITLE
undefined reference to `apr_pool_mutex_set'

### ISSUE THREAD

**Issue by neocheema** [unispeech/unimrcp#206]
I understand this is extremely similar to #159 , but I've followed all the steps and I'm still getting the exact same error. 

`../../platforms/libunimrcp-client/.libs/libunimrcpclient.so: undefined reference to `apr_pool_mutex_set'`

Btw, I'm building on CentOs 6. The commands that I ran as "root" were:

```
tar -zxvf unimrcp-deps-1.5.0.tar.gz
cd unimrcp-deps-1.5.0
./build-dep-libs.sh
tar -zxvf unimrcp-1.5.0.tar.gz
cd unimrcp-1.5.0
./bootstrap
./configure
make
```
On this machine, I can see that another version of "apr" is already installed. Could that be in conflict with the apr installed by unimrcp-deps?

**Comment by achaloyan** [comment]
Most likely, system-wide or another version of APR is used instead. In ./configure output for unimrcp package, look at the following to make sure the correct path is determined.

  setting UNIMRCP_APR_INCLUDES to " -I/usr/local/apr/include/apr-1 "
  setting UNIMRCP_APR_LIBS to " -L/usr/local/apr/lib -lapr-1"

If not, then you would need to explicitly specify the APR location by using

./configure --with-apr=/usr/local/apr

**Comment by ScarlettXa** [comment]
> i got this error, because i install `libapr1-dev` by myself.
> 
> so i just `apt remove libapr1-dev ` ,`apt remove libaprutil1-dev`
> 
> rebuild ./build-dep-libs.sh again， everything is ok

Yes, it is right, thanks.

**Comment by ScarlettXa** [comment]
> i got this error, because i install `libapr1-dev` by myself.
> 
> so i just `apt remove libapr1-dev ` ,`apt remove libaprutil1-dev`
> 
> rebuild ./build-dep-libs.sh again， everything is ok

Yes, it is right, thanks.
