### ISSUE TITLE
Failed to compile asterisk-unimrcp with asterisk15.1.2

### ISSUE THREAD

**Issue by wavestudio** [unispeech/unimrcp#207]
I have compiled asterisk-unimrcp with asterisk15.1.2，but i failed and i get some errors like:
In file included from /usr/local/apr/include/apr-1/apr_thread_cond.h:28:0,
                 from res_speech_unimrcp.c:39:
/usr/local/apr/include/apr-1/apr_time.h:40:36: error: storage class specified for parameter 'apr_month_snames'
 APR_DECLARE_DATA extern const char apr_month_snames[12][4];
                                    ^
/usr/local/apr/include/apr-1/apr_time.h:42:36: error: storage class specified for parameter 'apr_day_snames'
 APR_DECLARE_DATA extern const char apr_day_snames[7][4];
                                    ^
/usr/local/apr/include/apr-1/apr_time.h:46:21: error: storage class specified for parameter 'apr_time_t'
 typedef apr_int64_t apr_time_t;
                     ^
/usr/local/apr/include/apr-1/apr_time.h:56:21: error: storage class specified for parameter 'apr_interval_time_t'
 typedef apr_int64_t apr_interval_time_t;
                     ^
/usr/local/apr/include/apr-1/apr_time.h:58:21: error: storage class specified for parameter 'apr_short_interval_time_t'
 typedef apr_int32_t apr_short_interval_time_t;
                     ^
In file included from ../include/ast_compat_defs.h:33:0,
                 from res_speech_unimrcp.c:28:
/usr/local/apr/include/apr-1/apr_time.h:88:13: error: expected declaration specifiers before 'apr_time_t'
 APR_DECLARE(apr_time_t) apr_time_now(void);
             ^
/usr/local/apr/include/apr-1/apr.h:496:38: note: in definition of macro 'APR_DECLARE'
 #define APR_DECLARE(type)            type 
                                      ^
In file included from /usr/local/apr/include/apr-1/apr_thread_cond.h:28:0,
                 from res_speech_unimrcp.c:39:
/usr/local/apr/include/apr-1/apr_time.h:91:31: error: storage class specified for parameter 'apr_time_exp_t'
 typedef struct apr_time_exp_t apr_time_exp_t;
                               ^
/usr/local/apr/include/apr-1/apr_time.h:98:1: warning: empty declaration [enabled by default]
 struct apr_time_exp_t {
 ^
/usr/local/apr/include/apr-1/apr_time.h:128:45: error: expected declaration specifiers or '...' before 'apr_time_t'
 APR_DECLARE(apr_status_t) apr_time_ansi_put(apr_time_t *result, 
                                             ^
/usr/local/apr/include/apr-1/apr_time.h:138:43: error: expected declaration specifiers or '...' before 'apr_time_exp_t'
 APR_DECLARE(apr_status_t) apr_time_exp_tz(apr_time_exp_t *result,
                                           ^
/usr/local/apr/include/apr-1/apr_time.h:139:43: error: expected declaration specifiers or '...' before 'apr_time_t'
                                           apr_time_t input,
                                           ^
/usr/local/apr/include/apr-1/apr_time.h:147:44: error: expected declaration specifiers or '...' before 'apr_time_exp_t'
 APR_DECLARE(apr_status_t) apr_time_exp_gmt(apr_time_exp_t *result, 
                                            ^
/usr/local/apr/include/apr-1/apr_time.h:148:44: error: expected declaration specifiers or '...' before 'apr_time_t'
                                            apr_time_t input);
                                            ^
/usr/local/apr/include/apr-1/apr_time.h:155:43: error: expected declaration specifiers or '...' before 'apr_time_exp_t'
 APR_DECLARE(apr_status_t) apr_time_exp_lt(apr_time_exp_t *result, 
                                           ^
/usr/local/apr/include/apr-1/apr_time.h:156:43: error: expected declaration specifiers or '...' before 'apr_time_t'
                                           apr_time_t input);
                                           ^
/usr/local/apr/include/apr-1/apr_time.h:164:44: error: expected declaration specifiers or '...' before 'apr_time_t'
 APR_DECLARE(apr_status_t) apr_time_exp_get(apr_time_t *result, 
                                            ^
/usr/local/apr/include/apr-1/apr_time.h:165:44: error: expected declaration specifiers or '...' before 'apr_time_exp_t'
                                            apr_time_exp_t *input);
                                            ^
/usr/local/apr/include/apr-1/apr_time.h:173:48: error: expected declaration specifiers or '...' before 'apr_time_t'
 APR_DECLARE(apr_status_t) apr_time_exp_gmt_get(apr_time_t *result, 
                                                ^
/usr/local/apr/include/apr-1/apr_time.h:174:48: error: expected declaration specifiers or '...' before 'apr_time_exp_t'
                                                apr_time_exp_t *input);
                                                ^
/usr/local/apr/include/apr-1/apr_time.h:181:29: error: expected declaration specifiers or '...' before 'apr_interval_time_t'
 APR_DECLARE(void) apr_sleep(apr_interval_time_t t);
                             ^
/usr/local/apr/include/apr-1/apr_time.h:193:59: error: expected declaration specifiers or '...' before 'apr_time_t'
 APR_DECLARE(apr_status_t) apr_rfc822_date(char *date_str, apr_time_t t);
                                                           ^
/usr/local/apr/include/apr-1/apr_time.h:207:53: error: expected declaration specifiers or '...' before 'apr_time_t'
 APR_DECLARE(apr_status_t) apr_ctime(char *date_str, apr_time_t t);
                                                     ^
/usr/local/apr/include/apr-1/apr_time.h:219:40: error: expected declaration specifiers or '...' before 'apr_time_exp_t'
                                        apr_time_exp_t *tm);

my environment:
centos7
asterisk15.1.2
lastest unimrcp
lastest unimrcp-asterisk

**Comment by achaloyan** [comment]
It turns out ASTERISK_REGISTER_FILE macro is no longer available in Asterisk 15. The problem has been addressed in the following commit.
https://github.com/unispeech/asterisk-unimrcp/commit/a9664521a60b101e7c719915f9dd3b423e520a3f

For future, please post Asterisk related issues to the corresponding sub-project
https://github.com/unispeech/asterisk-unimrcp/issues
