### ISSUE TITLE
enable pocketsphinx plugin

### ISSUE THREAD

**Issue by mradul17** [unispeech/unimrcp#209]
hi unimrcp,
how to enable pocketsphinx plugin ? how to build unimrcp for pocketsphinx
i see a argument ( --enable-pocketsphinx-plugin) older version. but that is missing in new version.

**Comment by achaloyan** [comment]
The old PocketSphinx plugin is no longer supported. See the corresponding page for more info.

http://unimrcp.org/pocketsphinx
