### ISSUE TITLE
ININ issue - Incompatibility with Inin "connection sharing policy"

### ISSUE THREAD

**Issue by bayramboyraz** [unispeech/unimrcp#212]
Hi Arsen,

There is an issue with a ININ - UniMRCP TTS installation.

In the log attached there is a line saying "Failed to Find Channel"

Basically, ININ side is sending MRCPv2 messages of a session using different connections. I checked the RFC, which says that connection can be shared, but I could not see if RFC is clearly stating that all MRCP messages of a session has to be sent using the same connection. So, in UniMRCP implementation it looks like all MRCPv2 messages of a session are supposed to be sent/received using the same connection, but in ININ implementation no such assumption has been made, and different MRCPv2 messages of the same session have been sent on different connections.

UniMRCP version: 1.4.0
ININ 4.1

[inin-unimrcp_failed_to_find_channel.log](https://github.com/unispeech/unimrcp/files/1792197/inin-unimrcp_failed_to_find_channel.log)

**Comment by bayramboyraz** [comment]
In our code base of UniMRCP I have made the following addition:

`static mrcp_control_channel_t* mrcp_connection_channel_associate(mrcp_connection_agent_t *agent, mrcp_connection_t *connection, const mrcp_message_t *message)
{
	apt_str_t identifier;
	mrcp_control_channel_t *channel;
	if(!connection || !message) {
		return NULL;
	}
	apt_id_resource_generate(&message->channel_id.session_id,&message->channel_id.resource_name,'@',&identifier,connection->pool);
	channel = mrcp_connection_channel_find(connection,&identifier);
	if(!channel) {
		channel = apr_hash_get(agent->pending_channel_table,identifier.buf,identifier.length);
		if(channel) {
			apr_hash_set(agent->pending_channel_table,identifier.buf,identifier.length,NULL);
			mrcp_connection_channel_add(connection,channel);
			apt_log(APT_LOG_MARK,APT_PRIO_INFO,"Assign Control Channel <%s> to Connection %s [%d] -> [%d]",
				channel->identifier.buf,
				connection->id,
				apr_hash_count(agent->pending_channel_table),
				apr_hash_count(connection->channel_table));
		}
	}

	//if there is no channel found on the connection, then search it on another connection - Bayram Boyraz 13.03.2018 {{
	if (!channel)
	{
		mrcp_connection_t *current;
		current = connection;
		while (current->link.next->channel_table)
		{
			current = current->link.next;
			channel = mrcp_connection_channel_find(current, &identifier);
			if (channel)
			{
				apt_log(APT_LOG_MARK, APT_PRIO_INFO, "Found Channel <%s> assigned to another Connection %s",
					channel->identifier.buf,
					current->id);
				return channel;
			}
		}

		current = connection;

		while (current->link.prev->channel_table)
		{
			current = current->link.prev;
			channel = mrcp_connection_channel_find(current, &identifier);
			if (channel)
			{
				apt_log(APT_LOG_MARK, APT_PRIO_INFO, "Found Channel <%s> assigned to another Connection %s",
					channel->identifier.buf,
					current->id);
				return channel;
			}
		}
	}
	//}}

	return channel;
}`

This way it can go through other connections to find the channel. I hope this does not cause any bugs though.

**Comment by achaloyan** [comment]
As we clarified this issue with Bayram offline, this is not the intended behavior, defined by the specification. That is why the issue won't be addressed on the UniMRCP server side.
