### ISSUE TITLE
MRCPv2 Resource Discovery not workling

### ISSUE THREAD

**Issue by schlagert** [unispeech/unimrcp#213]
I just noticed that resource discovery does not work correctly when using MRCPv2.

Steps to reproduce (Version is 1.5.0):
* Install a unimrcp server
* Configure the unimrcpclient configuration to use MRCPv2
* Use the `unimrcpclient` utilities' discovery app against the server, e.g. `run discover uni2`

The application only reports the last resource advertised in the server SDP.

The problem seems to be in `mrcp_sdp.c:mrcp_descriptor_generate_by_sdp_session`. The code does only create one `mrcp_control_descriptor_t` per SDP `application` m-line.

**Comment by achaloyan** [comment]
Right. Implementation of the resource discovery has been incomplete. There is another issue on the client side that I would like to address, when have some time. Let's see...

**Comment by schlagert** [comment]
I'll file a PR if I'm able to fix it.

**Comment by schlagert** [comment]
This issue got resolved in #216
