### ISSUE TITLE
ubuntu xenial package problem

### ISSUE THREAD

**Issue by dias3000** [unispeech/unimrcp#214]
I'm not sure where to submit this issue.
I have installed asterisk package according to this quide
https://unimrcp.org/manuals/html/AsteriskDebInstallationManual.html
and found out that package asterisk-modules_1:13.17.0-xenial_amd64.deb has no module res_rtp_asterisk.so and this means that asterisk doesn't work 

rtp_engine.c:435 ast_rtp_instance_new: No RTP engine was found. Do you have one loaded?

**Comment by achaloyan** [comment]
This issue belongs to Asterisk integration and should have been reported to unispeech/asterisk.

Anyway, you are right res_rtp is disabled in binary packages built for Ubuntu 16. You may either use packages made for CentOS 7 or older ones made for Ubuntu 14. 

Of course, you can build all these components from source too.
