### ISSUE TITLE
Failed to set language other than en-US in kaldi plugin

### ISSUE THREAD

**Issue by qin** [unispeech/unimrcp#215]
Tested the kaldi plugin according to: 

http://unimrcp.org/manuals/html/KaldiSRDebInstallationManual.html#_Toc505625748

when modifying the language tag ```zh-CN``` under kaldi-server section of ```/opt/unimrcp/conf/umskaldisr.xml```:

![image](https://user-images.githubusercontent.com/416060/38481288-7dc339cc-3bfc-11e8-948a-e4cfac4573d8.png)

then start ```umc``` and ```run bsr1```, the request sent actually contains ```language=en-US```, resulting in ```language unsupported``` error:

![image 1](https://user-images.githubusercontent.com/416060/38481296-88312cd4-3bfc-11e8-88de-578ff24200cb.png)

**Comment by achaloyan** [comment]
See how the language needs to be set.

https://unimrcp.org/manuals/html/KaldiSRUsageManual.html#_Toc505698835

If the Speech-Language header field is not explicitly specified in a request sent from MRCP client, then the language currently defaults to en-US. That's why the error.
