### ISSUE TITLE
Documentation claims "one or more" media engines may be specified

### ISSUE THREAD

**Issue by ladenedge** [unispeech/unimrcp#217]
The [server <profile> documentation](http://www.unimrcp.org/manuals/html/ServerConfigurationManual.html#_Toc477709030) shows the following:

> `<media-engine>` | References one or more media engines.

It does not appear to be possible to reference multiple media engines (for, say, a [round robin approach](https://groups.google.com/forum/#%21topic/unimrcp/NDJeKt5gT9w)), as I believe the [relevant source code](https://github.com/unispeech/unimrcp/blob/master/platforms/libunimrcp-server/src/unimrcp_server.c#L918) does not allow for multiple engine names:

```
if(strcasecmp(elem->name,"media-engine") == 0) {
   media_engine = mrcp_server_media_engine_get(loader->server,cdata_text_get(elem));
}
```

where `mrcp_server_media_engine_get()` does a simple hash table lookup by name.

(Obviously this precludes multiple **media-engine** elements as well, as in

```
<mrcpv2-profile id="uni2">
  <media-engine>Media-Engine-1</media-engine>
  <media-engine>Media-Engine-2</media-engine>
  <!-- etc.. -->
</mrcpv2-profile>
```

In this case, only the last engine will be added to the profile.)

**Comment by achaloyan** [comment]
You can define multiple media engines and have one media engine per profile. 

It is currently not possible to define multiple media engines per server profile. This functionality was implemented for the client stack only.
