### ISSUE TITLE
3rd Party ASR Integration concurrency handling

### ISSUE THREAD

**Issue by krishnamohan191** [unispeech/unimrcp#218]
I had integrated ASR successfully by creating a socket connection in demo_recog_result_load() (demo_recog_engine.c) for communication between UniMrcp Server and ASR.

Now I have to handle concurrency between UniMrcp Server and ASR.
Scenario:
UniMrcp Client1 - sent audio data
UniMrcp Server - processed audio data and sent the same to ASR.
Before ASR response reception,
UniMrcp Client2 - sent audio data
But UniMrcp Server - is waiting for the response from ASR for the first client request, before sending Client2 audio data to ASR.
Once First response received, the second request has been sent to ASR.

It seems RTP session is not enabled for the second one before the client1 session is finished.

Can you please tell me how to handle above concurrency scenario.

**Comment by rmalav15** [comment]
I am also interested in knowing this.
@achaloyan , can you please comment on this?

**Comment by achaloyan** [comment]
This question is answered here:
https://groups.google.com/forum/#!topic/unimrcp/dzfnSWINNtU

Please do not post the same question to two different sources.
