### ISSUE TITLE
mpf_context_factory_process crashes

### ISSUE THREAD

**Issue by debdeepdas** [unispeech/unimrcp#219]
We have developed an application to over UniMRCP client. On running speech rec, it crashed at mpf_context_factory_process. 

[Windbg output.txt](https://github.com/unispeech/unimrcp/files/2079890/Windbg.output.txt)
[ErrorScreenShot.docx](https://github.com/unispeech/unimrcp/files/2079891/ErrorScreenShot.docx)

**Comment by achaloyan** [comment]
Your client application most likely passes or deals with an invalid data pointer on mpf callbacks. Note that the callbacks are called once SDP session is established and stopped only when session is teared down. It is up to your application to take care of data pointers you may be referencing from the mpf callbacks.
