### ISSUE TITLE
integrating Avaya with UniMRCP ，Reject Unexpected

### ISSUE THREAD

**Issue by yezhwi** [unispeech/unimrcp#220]
When integrating Avaya with UniMRCP, an error was reported:

Reject Unexpected TCP/MRCPv2 Connection 192.168.*.*:5060 <-> 2*1.1*.2.*:49427

How do you configure it? please

**Comment by achaloyan** [comment]
The provided information is not enough to provide any definite answer. I would guess UniMRCP server is located behind NAT, and is not configured accordingly.

You may check configuration examples provided in Section 4.

http://unimrcp.org/manuals/html/ServerConfigurationManual.html

If it does not help, you would need to provide the detailed topology of your network, configuration and logs of UniMRCP server, plus a network capture containing the session establishment phase.

**Comment by achaloyan** [comment]
This issue is being closed since no further input was provided.
