### ISSUE TITLE
LNK1104 cannot open file " .lib"

### ISSUE THREAD

**Issue by bluerising1** [unispeech/unimrcp#222]
Hi, I'm trying to build the unimrcp 1.5 ver open source code on Visual studio 2017 with no edit to the code but end up getting this link error shown below;

" **Error	LNK1104	cannot open file 'libunimrcpserver.lib mrcpsofiasip.lib mrcpunirtsp.lib unirtsp.lib mrcpserver.lib mrcpv2transport.lib mrcpsignaling.lib mrcpengine.lib mrcp.lib mpf.lib aprtoolkit.lib libaprutil-1.lib libapr-1.lib libsofia_sip_ua.lib ws2_32.lib winmm.lib'**	"

These libraries are created in the ..\Debug\lib folder while building and I have tried including this path explicitly almost everywhere but with no luck. 

"output_log.txt" is attached with the post, which shows the entire unimrcp project build log.

[output_log.txt](https://github.com/unispeech/unimrcp/files/2212523/output_log.txt)

I'm sure there is something that I am missing, if anyone could point in the right direction it would be of great help. Thanks!

**Comment by achaloyan** [comment]
Hi,

It does not seem you are using the released version. I noticed an additional module/plugin in the build log. The dependencies of the projects might be missing in your solution.

Please use the original release and compare with what you have.
