### ISSUE TITLE
Segmentation fault when input space on the server console(suggestion)

### ISSUE THREAD

**Issue by liuminggg** [unispeech/unimrcp#223]
version unimrcp-1.5.0
at src/uni_cmdline.c:29 
char * name  seems to be NULL ,returned by apr_strtok,and strcasecmp  cause Segmentation fault 

`
static apt_bool_t cmdline_process(mrcp_server_t *server, char *cmdline)
{
	apt_bool_t running = TRUE;
	char *name;
	char *last;
	name = apr_strtok(cmdline, " ", &last);

	if(strcasecmp(name,"loglevel") == 0) {
		char *priority = apr_strtok(NULL, " ", &last);
		if(priority) {
			apt_log_priority_set(atol(priority));
		}
	}`

**Comment by achaloyan** [comment]
Thanks. Fixed in f6bcaafcb0d71135e201d0e192be73a179d52ce3.
