### ISSUE TITLE
Will demo_synth_engine_close method be called when UniMRCP terminated

### ISSUE THREAD

**Issue by songday** [unispeech/unimrcp#228]
I started `unimrcpserver` without `-d` option, when I terminated UniMRCP program by 'Ctrl-C', I didn't see my log printed, the log I added in `demo_synth_engine_close` method of demo-synth-plugin.

Since I used `malloc` in `demo_synth_engine_open` method, I'm afraid there's memory leak if `demo_synth_engine_close` didn't called. ( I added `free` in this method )

**Comment by achaloyan** [comment]
If you terminate the process abnormally by 'Ctrl-C', then the corresponding methods will not be called. However, if you type 'quit' in the console (or stop the service), then the close() method of your plugin will be invoked.
