### ISSUE TITLE
An error in Bing SS plugin document

### ISSUE THREAD

**Issue by ywliu** [unispeech/unimrcp#229]
Hi,

As I upgraded Unimrcp Bing SS plugin to 1.6.0 and changed the auth endpoint and auth key in /opt/unimrcp/data/cognitive.subscription.key  in accordance with Section 5.2 of the document here :  http://www.unimrcp.org/manuals/html/BingSSDebInstallationManual.html

However, for auth-endpoint, your table says:

Authentication Endpoint | URI 
Bing Speech (non-regional) | https://api.cognitive.microsoft.com/sts/v1.0
Speech Service (regional) | https://$region.api.cognitive.microsoft.com/sts/v1.0

After numerous failures, I found out at least for regional SS, it should be like (in our case) :
https://eastasia.api.cognitive.microsoft.com/sts/v1.0/issueToken 

with the "**issueToken**" suffix in the URI or it would never succeed.

**Comment by achaloyan** [comment]
You have mixed up a few things. First of all, you do not have to change anything in your service credentials while upgrading to 1.6.0.

As you may know, Microsoft deprecated Bing API, which can still be used until Oct 2019. Instead, there is a new Speech API, which requires new credentials and also the format of cognitive.subscription.key for UniMRCP is different. The newer releases of UniMRCP Bing plugins support both APIs. You may find more details in this post.
 
[Transition from Microsoft Bing Speech to Speech Service](https://groups.google.com/forum/#!topic/unimrcp/MD9i-kSl3Nk)

Again, if your intention is to continue using the old Bing API for now, then you do not need to make any changes in cognitive.subscription.key that you had installed prior to upgrading to 1.6.0.

**Comment by ywliu** [comment]
Hi,
Though this is not a place to discuss tech support, I'd still like to clarify something :

1. We upgraded to 1.6.0 out of necessity.  Our service has been running months well but suddenly on Dec 3, 2018, it couldn't use the old non-regional API any more.  We tried several new keys, etc. ,  failing to revive it so we decided to switch to use the regional API.

2. We could not make it connect to the regional API endpoint with our old 1.5.4 plugin with the format of cognitive.subscription.key, we decided to upgrade to 1.6.0, though the document says it should be with 1.5.0+.

3.  We found the regional Auth endpoint URI in the document didn't work (always 401 error returned).   We need to append "**issueToken**" iso it eventually worked.

4. The bug report was simply to point out there might be some documentation error. If there is not , then sorry for the wrong bug report. I have modified the original report hoping it could be a little clearer.

Hoffmann

**Comment by achaloyan** [comment]
Hi Hoffmann,

Thanks for your clarification.

1. This must be coordinated with Microsoft. Though, it is apparent that sooner or later the upgrade is unavoidable.
2. There are different version numbers in place. The actual plugin version number can be retrieved from the log statement. For example: 
      BINGSS Plugin Version [1.5.2] Date [2018-11-15].
There are also RPM and deb package numbers which denote a version of UniMRCP server the plugin is built for: either 1.5 or 1.6.
3. You are actually right that the "issueToken" is required on the auth endpoint, and the document is kind of misleading. On the other hand, the document states that the auth endpoint must be collected from the corresponding speech resource in your Azure portal, whatever it is.
4. Understood. Thanks. The document will be updated.

**Comment by achaloyan** [comment]
3. The updated document has been published.
