### ISSUE TITLE
The confidence attribute in interpretation should be an integer from 0-100

### ISSUE THREAD

**Issue by godhand4826** [unispeech/unimrcp#231]
I'm studying the NLSML(Natural Language Semantics Markup Language).
I found there is a little bit weird.
Here is the result file of the recog demo in this project.
https://github.com/unispeech/unimrcp/blob/7794d214c469ec3ab08d58b84880630c41144f31/data/result.xml#L3
Due to the [w3_spec](https://www.w3.org/TR/nl-spec/#interpret) it should be "97" instead of "0.97".
Correct me if I'm wrong.
Have a good day.

**Comment by michaelplevy** [comment]
The document you are [referencing ](https://www.w3.org/TR/nl-spec/)is a working draft. In "Status of this Document" it says:
> It is a draft document and may be updated, replaced, or obsoleted by other documents at any time. It is inappropriate to use W3C Working Drafts as reference material or to cite them as other than "work in progress".

I **_believe_** the MRCP v2 group took the work that had been done on NLSML and incorporated it into their own work. They took a snapshot of the NLSML work and incorporated it into [RFC-6787](https://tools.ietf.org/html/rfc6787).

Notice that [RFC-6787 in section 6.3](https://tools.ietf.org/html/rfc6787#section-6.3) says:

> 6.3.  Generic Result Structure
>    The Natural Language Semantics Markup Language
>    (NLSML), an XML markup based on an early draft from the W3C, is the
>    default standard for returning results back to the client.  Hence,
>    all servers implementing these resource types MUST support the media
>    type 'application/nlsml+xml'.

RFC-6787 incorporates its own [NLSML schema](https://tools.ietf.org/html/rfc6787#section-16.1). In that schema, confidence is a float between 0.0 and 1.0.

**Comment by godhand4826** [comment]
Ok, I got it. Thanks.
