### ISSUE TITLE
"Waveform-Uri" should be "Waveform-URI"

### ISSUE THREAD

**Issue by lizhenghn123** [unispeech/unimrcp#235]
https://github.com/unispeech/unimrcp/blob/7794d214c469ec3ab08d58b84880630c41144f31/libs/mrcp/resources/src/mrcp_recog_header.c#L76
"Waveform-Uri" may be should write "Waveform-URI", see MRCPv2(rfc 6787）: https://tools.ietf.org/html/rfc6787#section-9.4.8. Or:

![image](https://user-images.githubusercontent.com/4832041/56106290-01590600-5f73-11e9-8afa-ab0c4db04b4c.png)

**Comment by michaelplevy** [comment]
6.2.  Generic Message Headers

> Each header field consists of a  name followed by a colon (":") and the value.  **Header field names are case-insensitive**.

https://tools.ietf.org/html/rfc6787#section-6.2

**Comment by lizhenghn123** [comment]
Thank you, i miss it.
