### ISSUE TITLE
end point url not allowing extra parameters

### ISSUE THREAD

**Issue by rajeshganji** [unispeech/unimrcp#237]
HI we are using customer bing streaming api. our configuration is as below 

{
    "auth-endpoint": "https://eastasia.api.cognitive.microsoft.com/sts/v1.0/issueToken,
    "auth-key": "83b03XXXXXXXXXXXXXX",
    "stt-endpoint" : "https://eastasia.stt.speech.microsoft.com/speech/recognition/interactive/cognitiveservices/v1?cid=38XXXXXXX"
}

It is not supporting extra parameter appending to stt-endpoint (cid=38xxxx) not get passed,  
could you please support this. 

Thanks,

**Comment by achaloyan** [comment]
Right, custom language models are not currently supported. Subject to a change request.

**Comment by achaloyan** [comment]
This feature has already been implemented in the latest Bing/Azure plugins.
