### ISSUE TITLE
[WARN]   Not Supported Media-Type [audio/basic]

### ISSUE THREAD

**Issue by syrbuov** [unispeech/unimrcp#238]
Hi,
I tried to use unimrcp server and google ss and sr plugins:
unimrcp-server.x86_64   1.6.0-1.el7
unimrcp-yandex-sr.x86_64   1.6.3-1.el7                  
unimrcp-yandex-ss.x86_64   1.6.2-1.el7 
As a mrcp client is used a cisco voice router(ios 12.4(15)T14)
The spech recognition doesn't work because of the recognizer-error:
 **[WARN]   Not Supported Media-Type [audio/basic]**

MRCP message from client is 
MRCP/2.0 516      RECOGNIZE  2
Channel-Identifier: a5d8de7d954f4d88@speechrecog
Speech-Language: en-US
Confidence-Threshold: 0.50
Sensitivity-Level: 0.50
Speed-Vs-Accura
cy: 0.50
Cancel-If-Queue: false
Dtmf-Interdigit-Timeout: 10000
Dtmf-Term-Timeout: 0
Dtmf-Term-Char: #
No-Input-Timeout: 10000
N-Best-List-Length: 1
Logging-Tag: 27
Content-Base: tftp://192.168.137.1/
**Media-Type: audio/basic**
Start-Input-Timers: false
Content-Type: text/uri-list
Content-Length: 30

I cannot change media-type on cisco router.

[complete log.txt](https://github.com/unispeech/unimrcp/files/3185931/complete.log.txt)

**Comment by achaloyan** [comment]
Hi,

The MRCP header field Media-Type is normally controlled by the VoiceXML property "recordutterancetype". You may set that property to "audio/x-wav" from your VoiceXML application. See Section 7.1

https://www.w3.org/TR/voicexml21/#sec-reco_reco

**Comment by syrbuov** [comment]
Yes, it works.
