### ISSUE TITLE
mrcp server logs problem

### ISSUE THREAD

**Issue by wujsy** [unispeech/unimrcp#239]
Hi, I haved develop a recog plugin in unimrcp framework, but when I wanted to log the server info, the  file was so big and unreadable, and my print log is not much.
here is my run command in background:
nohup ./unimrcpserver > log.txt 2>&1 &
so, what is the problem?

**Comment by michaelplevy** [comment]
Check the file conf/logger.xml
How is your logging configured.

I don't think you want to redirect stdout and stderr at the command line. You can use the -o and -l options to control log output and override the logger.xml config:
 -o [--log-output] mode   : Set the log output mode. (0-none, 1-console only, 2-file only, 3-both)
 -l [--log-prio] priority : Set the log priority. (0-emergency, ..., 7-debug)

**Comment by wujsy** [comment]
@michaelplevy, thanks for your reply, I will try
