### ISSUE TITLE
How can support G729?

### ISSUE THREAD

**Issue by yule2001** [unispeech/unimrcp#240]
I want to connect a call center, they send audio's codec is G729. So  I wonder how can add support codec G729?

**Comment by achaloyan** [comment]
What IVR platform do you use? Normally, IVR should be capable of transcoding g729 to g711. The latter can be used on the MRCP leg.

**Comment by yule2001** [comment]
I don't know. It owned by other company. I want to get phone audio from there , and send to the ASR engine.
So, it is possible to suppoert G729 ? My unimrcp version is 1.6.0

**Comment by achaloyan** [comment]
No, UniMRCP server does not support g729.
