### ISSUE TITLE
When Offline, server should respond with 503 to SIP Options request

### ISSUE THREAD

**Issue by michaelplevy** [unispeech/unimrcp#242]
When in Offline mode, the MRCP server responds with a 503 in mrcp_sofiasip_server_agent.c when mrcp_sofia_on_call_receive() is called. This will prevent the server from answering a new call. 

However, some voice browsers appear to use SIP OPTIONS resource discovery to determine if a server is online and alive. MRCP server should use similar approach to return 503 in mrcp_sofia_on_resource_discover() when in offline mode.

**Comment by michaelplevy** [comment]
I haven't gotten to fully test this, but I think the attached patch will fix this.

[Report.patch.txt](https://github.com/unispeech/unimrcp/files/3429000/Report.patch.txt)

**Comment by achaloyan** [comment]
Agree with the description of the problem. I'll try to review the behavior and apply the patch during these days. Thanks.

**Comment by achaloyan** [comment]
Fixed in 184025323a26c6e1e4d52f17eb1de84482251197
