### ISSUE TITLE
How to output log to fixed file

### ISSUE THREAD

**Issue by wty4427300** [unispeech/unimrcp#245]
As the title suggests

**Comment by michaelplevy** [comment]
Are you talking about the log files unimrcpserver-00.log and unimcrpclient-00.log? Do you care about the client logs or server or both?

Do you mean you don't want the log files to roll over to sequential names when the reach a size limit? -00, -01, -02...

In v1.6, see conf\logfile.xml. You can control the default log file settings for:
- purge-existing - Indicates whether to delete existing log files on start-up.
- max-age - Lifetime of log files in days. Outdated log files are determined and deleted upon start-up and next rotation. **Set 0 for infinite**.
- max-count - Max number of log files to store. If reached, the oldest log file is deleted. **Set 0 for infinite**.
- max-size - Max size of log files in Mb.

Have you tried setting max-age and max-count to zero?

**Comment by wty4427300** [comment]
Thank you,it really helped me.
