### ISSUE TITLE
Is thread or process exit  when called recog_channel_destory()?

### ISSUE THREAD

**Issue by wujsy** [unispeech/unimrcp#251]
Do anyone know, when called recog_channel_destory(), is  a thread or process exit?
In other words, when a new  recog channel created , is it in a new thread or a new process?

**Comment by achaloyan** [comment]
I think you refer to the function in app_unimrcp module for Asterisk. If so, then the recognition is initiated from the same thread Asterisk channel functions are executed. The UniMRCP client library does not create or terminate threads per recognition. As for Asterisk itself, then yes, a new thread is launched per call.

**Comment by wujsy** [comment]
@achaloyan  thanks , got it
