### ISSUE TITLE
demo-synth only works for client-server on same machine

### ISSUE THREAD

**Issue by abylouw** [unispeech/unimrcp#252]
I am having trouble getting the demo-synth working when the unimrcp client and server are on different machines. The resulting "synthesized" file on the client machine contains only nulls. 

When the client and server are on the same machine then everything works as expected. There are no indications that anything has gone wrong when I examine the log files from the client or server. 

I am using unimrcp 1.6 on Ubuntu 18.04

**Comment by achaloyan** [comment]
You would basically need to set the IP addresses accordingly and make sure firewall does not block SIP, MRCP and RTP ports. Checl log statements "Close RTP Receiver/Transmitter" for the number of RTP packets actually received or sent by each party.

**Comment by abylouw** [comment]
Thanks, it was the firewall on RTP.
