### ISSUE TITLE
Cross platform behavior of engine name in config file

### ISSUE THREAD

**Issue by Mert84** [unispeech/unimrcp#258]
In unimrcpserver.xml config file we specify the engine name as :

```
<plugin-factory>
	<engine id="SestekSREngine" name="SestekSR" enable="true"></engine>
</plugin-factory>
```

which makes the unimrcppserver try to load :
	on windows : SestekSR.dll
	on linux : SestekSR.so

I would have expected this to be libSestekSR.so on linux. 
We are automatically generating our setups and want to use the same single config file on all platforms. This behavior is somewhat preventing this to be a trivial task.

I have checked the code and saw the attribute named "ext" has been used for a similar purpose, albeit as a postfix instead of prefix. As a backward compatible solution would it be reasonable if I were to add another attribute here named "add-native-prefix" whose default value is false if not specified?
if true it would add "lib" in front of the name of the .so file on linux. 

Mert Büyüktuncay

**Comment by achaloyan** [comment]
Hi Mert,

I am curious why you would expect a run-time loadable module (not a generic library) to have the lib prefix. This is not common for any of the platform I am aware of, neither there is such a recommendation or convention.

This is simply a matter of a proper Makefile directive.

**Comment by Mert84** [comment]
> I am curious why you would expect a run-time loadable module (not a generic library) to have the lib prefix. 
Hmm, now that you say this.
You are right, I was under the impression that this would always be a lib file.
