### ISSUE TITLE
Ubuntu Bionic undefined symbol apr_procattr_perms_set_register erorr

### ISSUE THREAD

**Issue by Rudolfmajstr** [unispeech/unimrcp#262]
Installing UniMRCP on Ubuntu Bionic from Ubuntu repository returned error when starting apache. Have no issues on Xenial. The cause should be in newer version of APR in Bionic version.

UniMRCP versions

> ii  uniapr                                1:1.5.2-bionic                                  amd64        UniMRCP edition of Apache Portable Runtime library
ii  uniapr-util                           1:1.5.4-bionic                                  amd64        UniMRCP edition of Apache Portable Runtime Utility library
ii  unimrcp-client                        1:1.5.0-bionic                                  amd64        UniMRCP client shared libraries and sample applications
ii  unimrcp-common                        1:1.5.0-bionic                                  amd64        UniMRCP common data
ii  unisofia-sip                          1:1.12.12-bionic                                amd64        UniMRCP edition of Sofia SIP library

APR version on Bionic

> ii  libapr1:amd64                         1.6.3-2                                         amd64        Apache Portable Runtime Library
ii  libaprutil1:amd64                     1.6.1-2                                         amd64        Apache Portable Runtime Utility Library
ii  libaprutil1-dbd-sqlite3:amd64         1.6.1-2                                         amd64        Apache Portable Runtime Utility Library - SQLite3 Driver
ii  libaprutil1-ldap:amd64                1.6.1-2                                         amd64        Apache Portable Runtime Utility Library - LDAP Driver

The error:

> /usr/sbin/apache2ctl configtest
/usr/sbin/apache2: symbol lookup error: /usr/sbin/apache2: undefined symbol: apr_procattr_perms_set_register
Action 'configtest' failed.
The Apache error log may have more information.

**Comment by achaloyan** [comment]
You may need to set up the library path for apache in such a way to use the APR library shipped with Bionic, as they apparently are not compatible with the version of APR installed with UniMRCP packages. Use `ldd /usr/sbin/apache2ctl` to check for the current path.

**Comment by Rudolfmajstr** [comment]
Hi, so I checked paths with ldd /usr/sbin/apache2 and there were dependencies on UniMRCP libs. I removed the entry from /etc/ld.so.conf.d/unimrcp.conf and apache starts normaly. Will this pose any issues to unimrcp client?
Also now I see al UniMRCP packages are removed from official Ubuntu repository. Why did this happen?

**Comment by achaloyan** [comment]
> Will this pose any issues to unimrcp client?

No. But to make sure the UniMRCP client or server uses the intended library, you may the check the path with ldd in the same way.

> Also now I see al UniMRCP packages are removed from official Ubuntu repository. Why did this happen?

Not sure what you mean, but all the UniMRCP packages are in place. If you refer to the Asterisk packages in particular, then the packages for Asterisk-16 are currently maintained but not Asterisk-13.  Check out the corresponding installation manuals for more info.
