### ISSUE TITLE
libexpat.la: file not recognized with CMake build

### ISSUE THREAD

**Issue by djimenezgallegos** [unispeech/unimrcp#267]
Hello, 

I have been trying to run the CMake build but when CMake is running I have an issue that says that it cannot find -laprutil-1.

> Scanning dependencies of target mrcpunirtsp
[ 59%] Building C object modules/mrcp-unirtsp/CMakeFiles/mrcpunirtsp.dir/src/mrcp_unirtsp_sdp.c.o
[ 60%] Building C object modules/mrcp-unirtsp/CMakeFiles/mrcpunirtsp.dir/src/mrcp_unirtsp_logger.c.o
[ 61%] Building C object modules/mrcp-unirtsp/CMakeFiles/mrcpunirtsp.dir/src/mrcp_unirtsp_server_agent.c.o
[ 61%] Building C object modules/mrcp-unirtsp/CMakeFiles/mrcpunirtsp.dir/src/mrcp_unirtsp_client_agent.c.o
[ 61%] Built target mrcpunirtsp
Scanning dependencies of target demorecog
[ 62%] Building C object plugins/demo-recog/CMakeFiles/demorecog.dir/src/demo_recog_engine.c.o
[ 62%] Linking C shared module demorecog.so
/usr/bin/ld: no se puede encontrar -laprutil-1
../../../libs/apr-util/xml/expat/libexpat.la: file not recognized: No se reconoce el formato del fichero
collect2: error: ld returned 1 exit status
plugins/demo-recog/CMakeFiles/demorecog.dir/build.make:248: recipe for target 'plugins/demo-recog/demorecog.so' failed
make[2]: *** [plugins/demo-recog/demorecog.so] Error 1
CMakeFiles/Makefile2:693: recipe for target 'plugins/demo-recog/CMakeFiles/demorecog.dir/all' failed
make[1]: *** [plugins/demo-recog/CMakeFiles/demorecog.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

I have been looking what could be wrong but I cannot find the issue. I have no previous experience with libtool so maybe is something related that I am not noticing. 

That being said using the install procedure with Makefiles works perfectly.
If you can tell me what I'm missing it would be great :)

Thank you in advance!

**Comment by achaloyan** [comment]
Hello,

Do you have expat-devel installed?

**Comment by djimenezgallegos** [comment]
Hello,

First, it worked! Thank you. I forgot that package for sure.

Well I close this issue but I had to modify a CMake file in order complete the build. 
I'll make sure I am not missing anything. 

But anyways thank you for your answer :)
