### ISSUE TITLE
Add logging tag as an input parameter to a built-in grammar

### ISSUE THREAD

**Issue by zheka-13** [unispeech/unimrcp#272]
Hi, we would like to add this feature.
Because freeswitch does not support setting Logging-Tag header
So the usage of input parameter would be a good alternative 

like this

{logging-tag=42,start-input-timers=false,no-input-timeout=50000,recognition-timeout=15000}builtin:speech/transcribe?projectid=translator-xpqlcp

**Comment by achaloyan** [comment]
This is on the roadmap. As a result, the use case would

`builtin:speech/transcribe?projectid=translator-xpqlcp;logging-tag=42`

**Comment by achaloyan** [comment]
Implemented in GSR 1.18.0
