### ISSUE TITLE
MAX_LOG_FILE_SIZE for log rotation is not working

### ISSUE THREAD

**Issue by andrenatal** [unispeech/unimrcp#281]
The constant `MAX_LOG_FILE_SIZE` here https://github.com/unispeech/unimrcp/blob/master/libs/apr-toolkit/include/apt_log.h#L32 is not working. 

The only way to change the size of the log files was hardcoding the maximum file size here: https://github.com/unispeech/unimrcp/blob/master/libs/apr-toolkit/src/apt_log.c#L1110 and replace `file_data->settings.max_size` by the desired value.

**Comment by achaloyan** [comment]
Have you tried to change the log file size from the configuration file [logfile.xml](https://github.com/unispeech/unimrcp/blob/master/conf/logfile.xml)?

**Comment by andrenatal** [comment]
Thanks.
