### ISSUE TITLE
Failed to Poll [MRCPv2-Agent-1] status: 22

### ISSUE THREAD

**Issue by andrenatal** [unispeech/unimrcp#282]
When I have the server under high load, sometimes I get the error below. Does anyone know what that can be?

`Failed to Poll [MRCPv2-Agent-1] status: 22`

Thanks in advance

Andre

**Comment by achaloyan** [comment]
Having "Failed to poll" statement is a very rare occasion which would indicate an error on the OS level. 

What OS is this?
How many concurrent connections do you have about that time?
Have you adjusted the number of max connections for the MRCPv2 agent in [unimrcpserver.xml](https://github.com/unispeech/unimrcp/blob/master/conf/unimrcpserver.xml#L96).

**Comment by andrenatal** [comment]
it was Linux. I can't tell how many connection I had at the point, but the problem is now gone after I fixed some other issues in my plugin. So am now closing this
