### ISSUE TITLE
just one thread to handle stream,default ?how to use many thread? thanks

### ISSUE THREAD

**Issue by winsnlife** [unispeech/unimrcp#287]

**Comment by winsnlife** [comment]
I looked at the source code, but unfortunately, I didn't find a place to give a stream processing thread to a certain identification channel. Can anyone give me a hint? If you know

**Comment by achaloyan** [comment]
Sorry, can you please elaborate on what you are trying to achieve. Are you doing client or server side integration?

In either way, take into consideration that UniMRCP is based on async event-driven architecture where a single thread is supposed to process and is actually capable of processing hundreds of concurrent requests.
