### ISSUE TITLE
I have a question about the multiple threads

### ISSUE THREAD

**Issue by busishengui** [unispeech/unimrcp#292]
I found that in the client , only one channel can be used in a session. So， Can you help me to solve the problem how to implement multi-threaded operation in the client ? thanks a lot

**Comment by michaelplevy** [comment]
You might do better in the forums for general questions like this - https://groups.google.com/g/unimrcp

**Comment by achaloyan** [comment]
The response is posted in [this ](https://groups.google.com/g/unimrcp/c/4PtJpc7D3xw/m/KgI5_UXLAQAJ)thread.
