### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by dragonsongohan** [unispeech/unimrcp#301]
Version: UniMRCP 1.7.0
MRCP V1 crash, Segmentation fault (core dumped), 
Would you give me some suggests please? That is backtrace gdb 

Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/local/unimrcp/bin/unimrcpserver -r /usr/local/unimrcp -o 3 -w'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  apt_header_field_alloc (pool=pool@entry=0x7ff08c04b1d8) at ../../libs/apr-toolkit/include/apt_string.h:46
46		str->buf = NULL;
[Current thread is 1 (Thread 0x7ff099d0e700 (LWP 14))]

![photo_2021-08-30_22-09-57](https://user-images.githubusercontent.com/12947223/131440798-f8d9b663-389e-417d-b935-0b7b2b709b04.jpg)
![Screenshot from 2021-08-31 11-08-50](https://user-images.githubusercontent.com/12947223/131440801-415a088e-efdf-4b7d-abf1-fa5e61b7ec41.png)
![Screenshot from 2021-08-31 11-08-45](https://user-images.githubusercontent.com/12947223/131440821-1997e694-d432-4ca3-8415-c94733d4b8c2.png)

**Comment by achaloyan** [comment]
Is this problem reproducible? Can you provide the logs?

**Comment by achaloyan** [comment]
Closing this issue for now. If you are able to reproduce the problem and provide the logs with a coredump, please feel free to reopen.
