### ISSUE TITLE
Possibility for more logging control

### ISSUE THREAD

**Issue by wdavies-git** [unispeech/unimrcp#302]
I noticed the mrcp log has different timestamp format than Asterisk and was wondering if it can be made configurable ? it was more noticeable because it is logging time as GMT and not server time. I searched documentation but only found reference to changing the logging severity.

**Comment by achaloyan** [comment]
You may checkout the logger configuration file for available options.

https://github.com/unispeech/unimrcp/blob/master/conf/logger.xml

It should log the server time, though.
