### ISSUE TITLE
RTSP buffer size V1

### ISSUE THREAD

**Issue by dragonsongohan** [unispeech/unimrcp#303]
I am currently using UniMrcp v1 RTSP, I am having a packet problem with a larger size of 1024 bytes, how do I send a packet of data > 1024. Thank you.

**Comment by achaloyan** [comment]
There should not be any limitation in the data size. Data larger than 1024 bytes will be segmented and streamed in multiple chunks over a TCP/IP connection.
 
If needed, you may change the buffer size from the source code: https://github.com/unispeech/unimrcp/blob/master/libs/uni-rtsp/src/rtsp_server.c#L31

This parameter can also be changed from configuration for MRCPv2 but not RTSP connections.
