### ISSUE TITLE
Client error: tport_vsend Invalid argument, nta: INVITE Invalid argument (22)

### ISSUE THREAD

**Issue by QrFaq** [unispeech/unimrcp#304]
Hi! I'm trying to connect to the docker with unimrcp-server on a remote machine, and got stuck with an error:

```
tport_vsend(0x7f3ee0006210): Invalid argument with (s=16 */REMOTEserverPUBLICip:18060)
nta: INVITE (963217549): Invalid argument (22) with */[REMOTEserverPUBLICip]:18060
```

I did a couple of tests, and here are my results:

Test 1 (remote server connection)
Remote Server OS: ubuntu 20.04
- Unimrcp: Unimrcp-dependencies 1.6.0 ; Unimrcp 1.6.0
- Docker has been built on the remote server for ubuntu 18.04/20.04
- Server Ports: open
Server cfg: i've used default cfg, but for server reasons has changed it (cause of services, etc)
Client OS: ubuntu 18.04
Clinet cfg: default + appropriate ports + <server-ip> property at client settings

Docker launch cmd:
`docker run --rm -p 16011-16014:16011-16014 -p 11544:11544 -p 11554:11554 -p 18060:18060 -p 18062:18062 -p 16006-16010:16006-16010 -p 18001:18001 -p 15060:15060 -p 14900:14900 -p 10554:10554 TESTIMGNAME`

And I'm having the error above at the client side, while docker server has launched properly.

Test 2
Although I did another local test on VM with ubuntu 20.04 (i.e. the client and the server are inside VM):

Server OS VM: ubuntu 20.04
- Unimrcp: Unimrcp-dependencies 1.6.0 ; Unimrcp 1.6.0 or 1.7.0 (tried both)
- Docker was built on VM for ubuntu 20.04
- No-docker build VM: на ubuntu 20.04
Server cfg: default or the same as aboth (ports only if needed)
Client OS VM: ubuntu 20.04
Client cfg:
- Variant A: default;
- Variant B: default with an addition property <server-ip>172.17.0.2</server-ip> (ip has taken from the server app); different ports if needed;
docker run -p 1544:1544 -p 8060:8060 -p 5001-5200:5001-5200 DOCKER_NAME

Test 3
Another try was on a local machine without VM:
server OS: ubuntu 18.04
- Unimrcp: Unimrcp-dependencies 1.6.0 ; Unimrcp 1.6.0
- Docker build for ubuntu 18.04 or no-docker variant

As a result I got the same error at the end.

Test 4
The working tests were on localhost only (os 18.04 or 20.04), i.e.
- no docker build: server (localhost) + client (localhost) + default settings
- docker build: docker with `--network host`
- Docker build on ubuntu 20.04 for 18.04 and 2-dockers has launched at the same network, like 172.17.0.2 and 172.17.0.3 with default settings (if the address of the server hasn't been set, then it gives tport_udp_error)

Test 5
After that, I've tried to configure remote docker-server with a client to work via tcp/udp only (expose on build stage, make ports public), and it gave the same error from the title.

Would you mind to tell, is there any way to overcome this issue? 

Thanks in advance.

cfg and logs in attachments
[log_conf.zip](https://github.com/unispeech/unimrcp/files/7995746/log_conf.zip)
[client.log](https://github.com/unispeech/unimrcp/files/7995748/client.log)
[server.log](https://github.com/unispeech/unimrcp/files/7995749/server.log)

**Comment by achaloyan** [comment]
Sorry, I am not able to carefully follow all your attempts. Maybe you can get started with the attached artifacts that are known to work.
[Docker.zip](https://github.com/unispeech/unimrcp/files/8006017/Docker.zip)

**Comment by QrFaq** [comment]
Thx, for a fast response and sharing. I did an additional study of SIP and architecture usability under NAT in details vs. RTSP. So, I should use RTSP in my case, and there is nothing wrong here.
I'm closing an issue.
