### ISSUE TITLE
Freeswitch crashed at unimrcp library

### ISSUE THREAD

**Issue by xlb0479** [unispeech/unimrcp#306]
My Freeswitch crashed accidentally, according to the dump info, looks like something wrong with unimrcp library.

Unimrcp library version 1.2.0

![image](https://user-images.githubusercontent.com/11763303/157386423-56747732-0c24-4463-b202-875229c33b0d.png)

**Comment by achaloyan** [comment]
Sorry, but I do not event recall what was in 1.2.0. Please consider updating to a newer version. The latest version of UniMRCP is 1.7.0.
