### ISSUE TITLE
Possibility custom response in recog plugin 

### ISSUE THREAD

**Issue by dragonsongohan** [unispeech/unimrcp#307]
How can I custom response in recog plugin? I want to response the audio in the recogin plugin, is it possible

**Comment by achaloyan** [comment]
Sorry, your intention is not very clear. Do you mean to send audio data back to the MRCP client in response to RECOGNIZE. If so, you can possibly do that by embedding raw data in the NLSML instance. Not all the platforms will be able to process this sort of responses, though.
