### ISSUE TITLE
UniMRCP Yandex Plugin SR Case insensitive

### ISSUE THREAD

**Issue by Timofeo** [unispeech/unimrcp#309]
Hi.

Result not-match

My test grammar:

<?xml version="1.0"?>

 <grammar mode="voice" root="transcribe">
        <rule id="transcribe">

          <one-of>
            <item>да<tag>Yes</tag></item>
            <item>нет<tag>No</tag></item>
            <item>незнаю<tag>No</tag></item>
            <item>не знаю<tag>No</tag></item>
         </one-of>
       </rule>
      </grammar>

Result from yandex: Не знаю

    -- <result>
    --   <interpretation grammar="session:grammar-0" confidence="1">
    --     <instance></instance>
    --     <input mode="speech">Не знаю</input>
    --   </interpretation>
    -- </result>") in new stack

completion-cause: 001

Thanks.

**Comment by achaloyan** [comment]
This question was posted and answered on the discussion group: https://groups.google.com/g/unimrcp/c/W3Wwkb-b7WY
