### ISSUE TITLE
No reply Local SDP after running for a while

### ISSUE THREAD

**Issue by franktz** [unispeech/unimrcp#313]
Hi. I'm facing a problem which has been bothering me for a long time. 
I use FS(mod_unimrcp) + unimrcp architecture, after running for a while(mod_unimrcp sends an offer with connection:existing to reuse an existing connection), unimrcpserver didn't reply Local SDP, and then FS close connection due to timeout and trigger Status 487 to unimrcpserver.
Why no reply Local SDP after running for a while? Can anyone offer any suggestions that come to mind? Thanks.

Here is FS error log:
`2022-10-20 10:30:40.370508 98.97% [ERR] mod_unimrcp.c:1914 (TTS-32564) SYNTHESIZER channel error!`

and UniMRCP log:
`2022-10-20 10:30:10.360508 [INFO] Remote SDP 0x7f6f88086d78 <new>
v=0
o=FreeSWITCH 922099379207179487 3775814598659152372 IN IP4 172.17.0.23
s=-
c=IN IP4 172.17.0.23
t=0 0
m=application 9 TCP/MRCPv2 1
a=setup:active
a=connection:existing
a=resource:speechsynth
a=cmid:1
m=audio 18131 RTP/AVP 8
a=rtpmap:8 PCMA/8000
a=recvonly
a=mid:1

2022-10-20 10:30:40.360508 [INFO] Receive SIP Event [nua_i_state] Status 487 Request Terminated [SIP-Agent-1]
2022-10-20 10:30:40.360508 [NOTICE] SIP Call State 0x7f6f88086d78 [terminated]`

**Comment by achaloyan** [comment]
See the response in https://groups.google.com/g/unimrcp/c/vKRilZZP4P0
