### ISSUE TITLE
how to get sip informations from unimrcp

### ISSUE THREAD

**Issue by xuzhaofangxzf** [unispeech/unimrcp#314]
I used unimrcp1.7.0, and i need to know the detail of SIP info.

I tried in the callback function mrcp_sofia_eventcallback in the file mrcp_sofiasip_server_agent.c.

the callback funtion is defined as:

static void mrcp_sofia_event_callback(
                            nua_event_t           nua_event,
                            int                   status,
                            char const           *phrase,
                            nua_t                *nua,
                            mrcp_sofia_agent_t   *sofia_agent,
                            nua_handle_t         *nh,
                            mrcp_sofia_session_t *sofia_session,
                            sip_t const          *sip,
                            tagi_t                tags[])
i can get sip info when the sofia-sip get INVITE from client, and call the callback, but when sofia-sip response to the client, it made the sip pointer NULL, so I can not get the SIP info.

**Comment by achaloyan** [comment]
The same as https://groups.google.com/g/unimrcp/c/fPvKv7GMC_o
