### ISSUE TITLE
the  "sip-session-expires"  trigger early

### ISSUE THREAD

**Issue by lizhenghn123** [unispeech/unimrcp#315]
I use unimrcp for server. When then client is "keep-alive" connection, but not send sip option msg.

I find that if client don't send option for heartbeat， unimrcp would re-send some sip signal to client.
 
I modify the "sip-session-expires"  from 600(default value) to 189216000(3 years), wish the unimrcp don't send any sip msg by itself.    But i find that  the "sip-session-expires"  timer would trigger earlier other than 3 years.

So did i miss some thing?  Can you give me some advice ? 
Thanks a lot!

**Comment by lizhenghn123** [comment]
may be set 0 for disable?

**Comment by achaloyan** [comment]
Have you tried to to set sip-min-session-expires as well. The timeout is negotiated via SIP offer/answer. What is the SIP INVITE received by the server?
