### ISSUE TITLE
Why speech_complete_timeout is set as mpf_activity_detector_silence_timeout?

### ISSUE THREAD

**Issue by akmitrich** [unispeech/unimrcp#322]
https://github.com/unispeech/unimrcp/blob/9913f23691b3a1b8a7e84be5ba25478031352158/plugins/demo-recog/src/demo_recog_engine.c#L298C4-L298C4
I think that speech complete timeout has another semantics and should be set using mpf_activity_detector_speech_timeout_set https://github.com/unispeech/unimrcp/blob/9913f23691b3a1b8a7e84be5ba25478031352158/libs/mpf/include/mpf_activity_detector.h#L55

**Comment by achaloyan** [comment]
While the demo plugin and VAD detector are provided for the demonstration purposes only, speech_timeout is used for detection of an activity in the audio stream when the caller just started to speak, and silince_timeout is for detection of an inactivity after the caller stopped speaking.
